### ISSUE TITLE
Replace faces image in 'Image bit comparer' interactive

### ISSUE THREAD

**Issue by caitlind** [uccser/cs-field-guide#1007]
The image currently used for the faces option in the [Image Bit Comparer interactive](http://csfieldguide.org.nz/en/interactives/image-bit-comparer/index.html) is a little... out of date... and needs replacing.

**Comment by courtneycb** [comment]
We should also adapt this interactive to work with portrait oriented images.

**Comment by courtneycb** [comment]
There is also a bug where 0 bits shows two colours.

![image](https://user-images.githubusercontent.com/16066822/59648528-7b0bab00-91d3-11e9-9096-85441a8475dd.png)
