### ISSUE TITLE
Glossary terms missing

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1017]
Now that we can easily see them in content on the website, we need to go back through it and add glossary terms to important words in the content

**Comment by eAlasdair** [comment]
## HELP WANTED

If anyone has noticed words in the guide that would be useful to have a glossary definition for, please let me know

**Comment by eAlasdair** [comment]
Potential terms to add, terms I think should be added for 3.0 are marked in bold:

**Also not that some terms are duplicated in multiple chapters. If we want the chapters to be standalone, then we need to include glossary definitions in all of them**

- Introduction chapter:
  - [ ] Computer
  - [ ] Digital device
  - [ ] **Programming/program** (defined in algorithms)
  - [ ] Interface
  - [ ] Software
  - [ ] **Binary**
- Algorithms Chapter
  - [ ] **Algorithm** (added later, could be moved up)
  - [ ] Data
  - [ ] pseudo-code
  - [ ] **Programming language**
  - [ ] **Complexity**
  - [ ] **Big O notation**
  - [ ] **adage**
  - [ ] analogy
  - [ ] Correctness
  - [ ] key concept
  - [ ] **Linear Search** (searches/sorts etc for consistency)
  - [ ] **Binary Search**
  - [ ] **Selection Sort**
  - [ ] Pattern
  - [ ] **Insertion Sort**
  - [ ] **Pivot** (noun)
  - [ ] **Mergesort**
  - [ ]  Sequencing/sequence
  - [ ] Iteration
  - [ ] computation
  - [ ] Parallelism
  - [ ] Timsort
  - [ ] **Artificial intelligence**
  - [ ] **Computer Vision**
  - [ ] **Hash/hashing**
  - [ ] Search Tree
  - [ ] Computer memory
  - [ ] Web server
  - [ ] **Theoretical**
  - [ ] **Empirical**
  - [ ] Hardware
  - [ ] Operating System
  - [ ] **Environment**
  - [ ] **Tractability**
- Programming Languages:
  - [ ] **programming/program**
  - [ ] **programming language**
  - [ ] Hardware
  - [ ] machine code
  - [ ] Interpreter
  - [ ] Assembler
  - [ ] Compiler
  - [ ] system
  - [ ] loop
  - [ ] **syntax**
  - [ ] variable
  - [ ] conditional
  - [ ] GUI
  - [ ] Arithmetic
  - [ ] Computer chip
  - [ ] Transistor
  - [ ] **Binary**
  - [ ] Circuit
  - [ ] High level Language
  - [ ] Low level language
  - [ ] Embedded system
  - [ ] Register
  - [ ] string
  - [ ] **hexadecimal**
  - [ ] Optimisation
  - [ ] RISC & CISC
  - [ ] script
  - [ ] ByteCode
  - [ ] **Regular Expression**
  - [ ] **Grammar** (regex)
  - [ ] Functional Programming

**Comment by taskmaker1** [comment]
bozo sort needs to be added to the glossary

**Comment by eAlasdair** [comment]
> bozo sort needs to be added to the glossary

Bozo *search* has been added to the glossary. We don't mention bozo *sort* in the FG so it has not been added

**Comment by JackMorganNZ** [comment]
FYI: Also it's bozo search and bogo sort. Not that it's important to remember 😆
