### ISSUE TITLE
Improve Word Filter interactive

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1020]
- The file should be loaded asynchronously, so that it doesn't lock up the webpage
- The word list should be under the interactive, so that it fits more neatly
- Consider making it a whole-page interactive only if it still doesn't fit neatly

**Comment by courtneycb** [comment]
The file is loaded asynchronously but the file contains roughly 250,000 words and are loaded into an array which is then iterated over. The browser freezes while the for loop is running over the array.

**Comment by eAlasdair** [comment]
The for loop is pretty much instantaneous, the (largely unavoidable) slowdown is when it goes to print all the words it matched. Best solution is to limit the number of words loaded at a time
