### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#103]
Add a debug mode accessed by tag on command line. Currently when an error occurs in the markdown parsing, a message is logged and the HTML is set to nothing (`''`). If debug mode is active, it sets the HTML to `<div class="markdown-error"></div>` which is styled red and displays on output.

This would allow authors to easily see on output where errors are occurring, to complement the log file.

**Comment by eAlasdair** [comment]
Previous system - outdated
