### ISSUE TITLE
Mobile navbar menu has no background

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1054]
This makes it very hard to see the menu items.

![image](https://user-images.githubusercontent.com/8001048/60401897-1e998a00-9bdc-11e9-8033-de20c9802dbe.png)

**Comment by courtneycb** [comment]
Also on mobile you cannot select 'Chapters' from this menu, it's scrolled down and you cannot scroll back up. Unsure if related to this issue or not.

**Comment by JackMorganNZ** [comment]
> Also on mobile you cannot select 'Chapters' from this menu, it's scrolled down and you cannot scroll back up. Unsure if related to this issue or not.

I haven't seen this issue, can you provide a screenshot?

**Comment by courtneycb** [comment]
Can't scroll up further from here. Also I have no idea why this image is so big sorry lol.

![Screenshot_20190702-071158_Samsung Internet](https://user-images.githubusercontent.com/16066822/60464394-94682900-9ca2-11e9-9f18-f39d0011ac30.jpg)

**Comment by eAlasdair** [comment]
I don't get this behaviour on my android phone

**Comment by courtneycb** [comment]
> I don't get this behaviour on my android phone

Interesting. Another member of the team gets this behaviour on their iPhone.

**Comment by courtneycb** [comment]
Created a new issue addressing the scrolling behaviour in #1068. 

The navbar background issue was resolved in #1064 so closing this issue.
