### ISSUE TITLE
Check table rendering

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#106]
Table rendering does not seem to be working, following the syntax given in writing-text.md. The raw ASCII characters just go in the output.

**Comment by JackMorganNZ** [comment]
Your table syntax appears to be correct (it renders correctly on [GitHub here](https://github.com/uccser/cs-field-guide/blob/40064d8b86c2fee356e642f0a969b983a302b4d4/text/curriculum-guides/ncea/en-assessment-guide-level-1-searching-algorithms.md)) so I will look into why it's not working in the output. Thanks, Heidi!
