### ISSUE TITLE
Instate the appendices menu as dropdowns instead of a separate page

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1063]
It's added time (and therefore frustration) to load a new page just for a menu

![image](https://user-images.githubusercontent.com/25916475/60407553-5c63d600-9c0f-11e9-8ffe-3de49171f124.png)

**Comment by JackMorganNZ** [comment]
Could you explain the proposed changes further?

**Comment by eAlasdair** [comment]
I thought about it more and realised I was mistaken and this definitely didn't exist in earlier development:

![IMG20190702100122](https://user-images.githubusercontent.com/25916475/60469408-a4870500-9cb0-11e9-97d9-be153c97e6d7.jpg)

Sorry about that confusion.

But I think it should be, at least in part. When I click the language button it doesn't take me to a new page, it just shows me the options.

I propose (on desktop); `curriculum guides`, `glossary` and `interactives` should be options in a dropdown menu, in the position of `curriculum guides`. And a second dropdown for the remaining appendices, in the position of `appendices`
![IMG20190702101501](https://user-images.githubusercontent.com/25916475/60469910-76a2c000-9cb2-11e9-90e1-f7ed000181a1.jpg)

**Comment by eAlasdair** [comment]
Closing for now, can be reopened if this becomes more of an issue
