### ISSUE TITLE
Section separator should only show after sections, not before

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#1065]
Personally I think the first separator shouldn't be there because there is no section before that one on the page. Feel free to close this if you think it should be this way. 

![image](https://user-images.githubusercontent.com/16066822/60468161-df873980-9cac-11e9-87ee-ef3f8d23d024.png)

**Comment by eAlasdair** [comment]
This also highlights the inconsistency we have - some chapter sections start with text (no heading), some start with headings

**Comment by JackMorganNZ** [comment]
Agreed, two points:
- As @timbellnz a few weeks ago, it's best to not having two headings against each other. We could easily add a sentence here to solve this.
- Removing the first one should be possible via CSS rules.
