### ISSUE TITLE
Main homepage icons align left on Firefox mobile screens

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1066]
![image](https://user-images.githubusercontent.com/25916475/60470177-9edeee80-9cb3-11e9-9a0c-c1bfae0c2f4d.png)

The alignment works well (edit: on firefox) on desktop and okay on tablet sizes but poorly on mobile because everything else is centered

**Comment by JackMorganNZ** [comment]
Probably a browser default to a particular rule (possibly the alignment of SVG paths within it's viewbox). Could you please post the browser and screen size?

**Comment by eAlasdair** [comment]
(Using screen sizes defined in the browser dev-tools)

**Comment by courtneycb** [comment]
Can confirm this issue.

**Browser**: Firefox v67.0.3
**Viewport**: 360 x 740 Pixels
**Operating System**: Android v9
**Device**: Samsung Galaxy S9

![rsz_screenshot_20190703-091053_firefox](https://user-images.githubusercontent.com/16066822/60546992-b4671d80-9d72-11e9-81eb-4ecc8c044696.jpg)
