### ISSUE TITLE
Strikethrough does not work

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#108]
I tried to use strikethrough, following the ~~striked out text here~~ syntax in the guide to syntax. It doesn't seem to work though. Look in text/curriculum-guides/ncea/en-assessment-guide-level-2-excellence-compression-run-length-encoding.md for an example of me attempting to use it.

**Comment by JackMorganNZ** [comment]
@Heidirose and I have discussed this issue, and have decided to not implement strikethrough currently. Strikethrough is a deprecated style, though can still be implemented by CSS styles. We think it's best to not use strikethrough where possible, as it's usage is confusing.
