### ISSUE TITLE
Unhelpful 'Player error' When viewing video on Firefox

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1088]
## Description

Firefox quantum 67.0.4 for Linux Mint

Whether something needs to be installed on my browser or there is some other issue I'm not sure, but I cannot play any of the videos for the following error:

![image](https://user-images.githubusercontent.com/25916475/60927315-99118a80-a2fd-11e9-85d8-82f9968c93e7.png)

This is probably relevant, though I haven't tried it yet:
http://techawakening.org/vimeo-videos-not-working-in-firefox-solution/2490/

**Comment by eAlasdair** [comment]
This page asks I contact Vimeo itself
https://vimeo.zendesk.com/hc/en-us/articles/115015677227-Troubleshoot-player-error-messages

**Comment by courtneycb** [comment]
This does not happen for me on Firefox 67.0.4 for Linux Mint

**Comment by eAlasdair** [comment]
I will close this because it seems like something on my end. Feel free to reopen if there are other cases
