### ISSUE TITLE
Old archived interactives don't load correctly

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1107]
We don't usually support archived material, but because we link to it from the main guide as a core interactive of a chapter, it should be fixed.

For example: https://archive.csfieldguide.org.nz/1.9.9/_static/widgets/CG/CG-mini-editor/main%20%28cutdown%29.html?info=%0AIn%20this%20interactive,%20try%20changing%20the%20scaling%20on%20the%20image%20%28it%20starts%20with%20a%20scaling%20factor%20of%2010%20in%20all%20three%20dimensions%29

```
Mixed Content: The page at 'https://archive.csfieldguide.org.nz/1.9.9/_static/widgets/CG/CG-mini-editor/main%20%28cutdown%29.html?info=%0AIn%20this%20interactive,%20try%20changing%20the%20scaling%20on%20the%20image%20%28it%20starts%20with%20a%20scaling%20factor%20of%2010%20in%20all%20three%20dimensions%29' was loaded over HTTPS, but requested an insecure stylesheet 'http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css'. This request has been blocked; the content must be served over HTTPS.
```

Possibly changing HTTP to HTTPS will fix the issue.

**Comment by eAlasdair** [comment]
From my experience that will fix it, but where is the code stored?

**Comment by JackMorganNZ** [comment]
On our old webfaction fileserver, I'll go into it now.

**Comment by courtneycb** [comment]
With the rebuild of `scene-editor` and `matrix-simplifier` (#1115) we no longer link to archived material from the main guide.
