### ISSUE TITLE
Parser Reorders Script Tags

### ISSUE THREAD

**Issue by Jamesernator** [uccser/cs-field-guide#111]
When pulling out interactives script tags are reordered alphabetically so something like:
```html
<script src="some-library-needed-first.js"></script>
<script src="main-program.js"></script>
```
becomes
```html
<script src="main-program.js"></script>
<script src="some-library-needed-first.js"></script>
```

which means main-program.js can run without its dependencies thereby breaking.

**Comment by Heidirose** [comment]
While trying to test a fix for a specific interactive, we discovered that it isn't alphabetical -- it is random. So sometimes interactives will work, and other times they won't.

**Comment by JackMorganNZ** [comment]
This is because they are added to a set to remove duplicates. We can easily switch this to a list and check if the item is in there, to achieve the same functionality and keep the order they are defined. Good find.
