### ISSUE TITLE
Pages longer than one page are not printed correctly

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1110]
When printing a page of content, it only shows the content on the current page. It's likely we need to revert the fixed navbar/content view, to a traditional layout.

**Comment by courtneycb** [comment]
This issue now only affects Firefox. Currently Firefox print preview breaks on anything that uses flex styling, see https://bugzilla.mozilla.org/show_bug.cgi?id=939897

**Comment by jimbonothing64** [comment]
Using the [graphics transformations page](https://www.csfieldguide.org.nz/en/chapters/computer-graphics/graphics-transformations/), Chrome 121, Firefox 122 and Safari 17 all print multiple pages now.
