### ISSUE TITLE
Fix formatting + check content for Computer Graphics

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#116]

**Comment by timbellnz** [comment]
Checked all text, moved NZ specific material to NCEA guide, added some extra jargon/curiosity material
commit ccb8a08ab1626f5d86743b04c72dfe8ef5ecf89a

**Comment by timbellnz** [comment]
Images and interactives are still missing; these need to be added and checked in context as some of the interactives contain explanatory text.

**Comment by JackMorganNZ** [comment]
I'm currently adding older images. I will also add links to older interactives (as it will be time consuming to recreate).

**Comment by eAlasdair** [comment]
Closed for inactivity, can be reopened with new info, or a new issue can be created
