### ISSUE TITLE
Fix formatting + check content for Formal Languages

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#117]

**Comment by timbellnz** [comment]
Have done first three sections; the interactives and images still need to be put in properly. Will work on second half soon, but just checking in the work so far:
commit 9f03f8a47ad0bf0c429d3d526f12f788483a5ab8

**Comment by timbellnz** [comment]
Some more minor fixes done to formatting and glossary, but second half still to be done
commit 7e9e91ff99ed99535aa7f8e47a4d44edd4abccd3

**Comment by timbellnz** [comment]
Whole chapter has now been checked. (Interactives and images still need to be made available).

NCEA relevant material has been moved to a new appendix file.

Commit 9afae5dc778593b6e767427f7f3df506a9b0a576
