### ISSUE TITLE
Pixel-viewer?

### ISSUE THREAD

**Issue by ibrahimLearning** [uccser/cs-field-guide#1188]
Thanks for your contribution. I am searching pixel viewer. Where is the source code of the pixel-viewer?

**Comment by courtneycb** [comment]
Hi there, thanks for your question.

You can find the `css` and `js` files here:
https://github.com/uccser/cs-field-guide/tree/develop/csfieldguide/static/interactives/pixel-viewer

and the template file here:
https://github.com/uccser/cs-field-guide/blob/develop/csfieldguide/templates/interactives/pixel-viewer.html

Thanks :) let me know if you have anymore questions.
