### ISSUE TITLE
Suggestion: Optional custom interactive thumbnails

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1198]
Some interactives really don't suit our current thumbnail generator &ndash; most notably Packet Attack and trAIning ground; which don't even display at the screen size the generator loads them in.

![image](https://user-images.githubusercontent.com/25916475/69387392-8e92e300-0d2a-11ea-8173-4b4123fbda60.png)

The generator is a very useful time-saver and works well for _most_ interactives, so I don't think it should be changed. Instead, I propose we add a search to it that checks if `<interactive>/thumbnail.extension` exists and if so, uses that instead of generating one. _Most_ thumbnails would still be generated, but the few that really don't work can still have thumbnails that actually reflect what they look like

Potential rules for such a default thumbnail:
- same size and format as a generated thumbnail
- no text (so internationalisation friendly)
- reflects the interactive better than the generated thumbnail
- reflects the interactive in its current state (recreate if the interactive is changed)

**Comment by JackMorganNZ** [comment]
You could also provide custom settings for loading each interactive, for example, a specific mode via an anchor, or certain dimensions.
