### ISSUE TITLE
Fix formatting + check content for Error Control Coding

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#120]

**Comment by timbellnz** [comment]
Basic formatting sorted out and minor corrections; still need to restructure check digit section for new interactives.
commit 29af9c15893e212ae233c6f358ada19f9c736910

**Comment by timbellnz** [comment]
error control chapter revised for new check digit interactives
commit 7e68e8b6b26bcb504a75192d1845ba1a15d30521
