### ISSUE TITLE
Processed image pixels not updating in jpeg compression interactive

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#1269]
When all values are set to zero, then some values are changed, the "Processed Image Pixels" panel is not updated.

There is also a style issue where the button styling for the interactive is applied to the search button in the navbar.

![image](https://user-images.githubusercontent.com/16066822/82509691-b984b500-9b5c-11ea-98a8-c3ddd856dfb8.png)

**Comment by eAlasdair** [comment]
The issue is that it's possible to erroneously swap the value of the two checkboxes (checked acts like it's not checked and vice versa). This led to the belief that panels weren't being updated.
