### ISSUE TITLE
LZSS compression interactive not encoding text correctly

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#1271]
For the example below it should replace all but the first 2 characters with a pointer.

![image](https://user-images.githubusercontent.com/16066822/82905099-89ec0780-9fb7-11ea-99a6-852728b772ca.png)

**Comment by eAlasdair** [comment]
New version is an improvement but ignores text that hasn't yet been encoded when encoding the next bit of text. For example:
`abababababababa` is encoded as `ab` `0-2` `0-4` `0-7`, but it should be `ab` `0-13`

According to Tim:
> It's might seem a bit odd, as the reference includes itself, but it all works out if you decode it.
