### ISSUE TITLE
Too much spacing when panel headings (summary) on multiple line.

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#130]
When a panel heading (summary) is too long to fit on one line and it is broken onto multiple lines, there is far too much spacing between the lines. This is going to be a problem particularly on mobile.

It is also currently possible for just the little arrow to be moved onto the next line. This looks very strange, as it is hanging outside of the box onto the text below.

**Comment by JackMorganNZ** [comment]
I will start looking into this as I'm currently working on panel code.
