### ISSUE TITLE
Add new attributes to Pixel Viewer interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1302]
The following features should be developed for Pixelmania:

1. A new URL parameter `hide-colour-code-picker` should hide the options to change the colour code type.
2. [This image](https://github.com/uccser/cs-field-guide/blob/develop/csfieldguide/static/interactives/image-bit-comparer/img/IMG_2223.jpg) should be added to the available set. 
3. A new URL parameter `pixelmania` should show a small Pixelmania logo above the interactive title in the menu.

**Comment by eAlasdair** [comment]
Can I get a copy of said Pixelmania Logo?

**Comment by JackMorganNZ** [comment]
- Logo sent via Slack
- The image is mine, and is under the standard project CC license.

**Comment by JackMorganNZ** [comment]
Could you also rename the photo `lake.png` when adding it to Pixel Viewer? Will make it nicer to reference in the URL.

**Comment by eAlasdair** [comment]
> Could you also rename the photo `lake.png` when adding it to Pixel Viewer? Will make it nicer to reference in the URL.

Was gonna say 'pier' but that also works :+1:
