### ISSUE TITLE
Some punctuation in headings is breaking formatting

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#131]
The parser does not correctly generate headings which have certain punctuation in them. The examples I have seen so far are : and /. Check the software engineering chapter for examples of this happening (the analysis, design, and testing sections all have a : in their headings).

**Comment by JackMorganNZ** [comment]
@Heidirose I believe this has been fixed, as I cannot recreate it.

**Comment by JackMorganNZ** [comment]
The error has now been found (more information from #164) so this is re-opened until solved.

**Comment by JackMorganNZ** [comment]
I've changed the way headings are detected to allow any characters except for `#` and new lines.
