### ISSUE TITLE
Scary Interfaces Broken Link

### ISSUE THREAD

**Issue by JayBigGuy10** [uccser/cs-field-guide#1316]
## Description

Clearly and concisely describe the issue or suggestion here:

There is a link in the scary interfaces drop down in this section https://csfieldguide.org.nz/en/chapters/human-computer-interaction/usability-heuristics/#aesthetics-and-minimalist-design

when this link is clicked it leads to a page stating "Your PHP installation appears to be missing the MySQL which is required for WordPress."

Perhaps if it exists download a copy of the page from the wayback machine and host it yourselves so it can be accessed on school networks? or find a suitable replacement page

### Checklist

*Change the space in the box to an `x` for those you have completed. You can also fill these out after creating the issue.*

- [ x] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] The platform(s)/software you are encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by eAlasdair** [comment]
Thankyou for letting us know! It will be fixed in the next release
