### ISSUE TITLE
Refactor explanation for "Common situations where layouts unexpectedly change"

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#132]
In the HCI chapter - it needs to be modified so that it is bullet points rather than a run on paragraph.

Assigning to Tim, as he can probably do a better job of it than me :-)

**Comment by timbellnz** [comment]
Done - turned into bullet points. New version has been pushed.

**Comment by Heidirose** [comment]
@timbellnz  Just a quick question, was it intentional to have semi colons at the end of each bullet point?

**Comment by timbellnz** [comment]
It was, but on reflection, making them full stops (and capitals) would be better.

**Comment by Heidirose** [comment]
Yeah I agree. I'll leave you to quickly fix that :-)

**Comment by timbellnz** [comment]
Done.
