### ISSUE TITLE
Expand on "Cognitive walk-through" project in HCI chapter

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#133]
Needs a bit more explanation :-)

**Comment by timbellnz** [comment]
I have split the project on how to do a Cognitive walkthrough into two, as it currently combined Think-aloud with Cognitive walkthrough. The two projects provide alternative ways to do a quick evaluation.

The NCEA curriculum guide for 1.44 has also been updated to mention the two projects.

commit 8c0c2f1f6bb994e87a79c533770422b8e7696ee9
