### ISSUE TITLE
SVG images missing from dev site

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#1331]
*The production site is fine.*

All SVG images [on the development site](https://cs-field-guide-dev.appspot.com/en/) are missing, including homepage images and chapter icons. Uninteractives that use SVG lines are unaffected.

![image](https://user-images.githubusercontent.com/25916475/95006686-56a33e80-0663-11eb-9ae5-21209446d5df.png)

There are no console errors. The divs for those images are empty:
![image](https://user-images.githubusercontent.com/25916475/95006717-bf8ab680-0663-11eb-8773-bf7e5b900bb8.png)

What the example should look like:
![image](https://user-images.githubusercontent.com/25916475/95006866-6cb1fe80-0665-11eb-9d98-82617ae12320.png)

Seen on Chrome and Firefox.
The production site, as well as running the develop branch locally, does not have this issue

**Comment by eAlasdair** [comment]
One possible cause could be #1315 as the SVGs are stored in the build folder, but so is the rest of the build so it seems unlikely

**Comment by eAlasdair** [comment]
We are currently unable to use our dev site, but including the commit above SVG images were successfully deployed in a CSFG release. So either:
- That was indeed the issue and none of the three folders can be ignored
- That was indeed the issue but only one or two need to be ignored, the rest are fine
- That was not the issue, but the issue is resolved in some other way
- That was not the issue, but the issue is limited to the dev site

**Comment by JackMorganNZ** [comment]
Fixed in 77eefa185b8dda33002ef991c7f8b1e83903c7e2
