### ISSUE TITLE
payment-interface interactive is even more frustrating than it is supposed to be in new version of guide

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#135]
On the old version of the guide, it looked like a valid interactive. On the new version, the greyed out and left aligned appearence makes it look like broken HTML. I suspect students will notice that more than the usability issues it is supposed to be illustrating :-)

**Comment by Marcus-SK** [comment]
I've made small style changes, like centering the interactive on medium/large screens and making the heading stand out, similarly to the other interactives on that page. Better already!
