### ISSUE TITLE
Possible mistake in 12.3.2 Using a formula to draw a line

### ISSUE THREAD

**Issue by anzeljg** [uccser/cs-field-guide#1358]
## Description

In section 12.3.2 you are using the following line equation: **y = mx + c**.

In the fifth paragraph of that section you write:

`See if you can work out the m and b values for a line from A to B, or you can calculate them using the following formulas`

Shouldn't there be **c** instead of a **b** in the sentence and the formula below?

**Comment by eAlasdair** [comment]
Thank you for letting us know!
