### ISSUE TITLE
Interactives/ Examples/ Images needed for heuristic: Aesthetic and minimalist design

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#139]

**Comment by timbellnz** [comment]
Examples of TV remotes given, curiosity on scary interfaces added

commit 7cd2115328e5684350736fb724a6c9a4ffb1c24b

**Comment by timbellnz** [comment]
Needs three images of remote controls to be added.

**Comment by timbellnz** [comment]
I've put the images in, but they may be a bit clunky. They're intended to be on the left/right of the text rather than between paragraphs, and the unexpanded version could be smaller.

**Comment by JackMorganNZ** [comment]
I've nearly fixed the wrapping of images, just need to do some final checking. The section with TV remotes looks so much nicer now!
