### ISSUE TITLE
Interactives/ Examples/ Images needed for heuristic: Help users recognize, diagnose, and recover from errors

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#140]

**Comment by Heidirose** [comment]
@timbellnz I just got this error with the sound on my computer (yes I'm using Windows. I only use it for certain gaming I swear!). Very unhelpful error -- you could use it in the field guide if you want.

![audio-error](https://cloud.githubusercontent.com/assets/7854960/11912064/3b9d7bc8-a691-11e5-91a6-0a978fc9613b.png)

**Comment by timbellnz** [comment]
"Unexpected error" example has been added. I have also added wording for the positive example from an alarm clock - yet to add an image, and then can commit changes.

**Comment by timbellnz** [comment]
Image of Android alarm clock added.

commit 090de627592435b137f57ae4c973cc555b826cbe
