### ISSUE TITLE
Tim needs to check over HCI chapter

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#141]
I have fixed all the formatting and modified a few minor things in the HCI chapter. Tim, can you please check over it? This page here allows easy comments/ review, although you might also like to generate guide so that you can see what it looks like in the field guide now.

https://github.com/uccser/cs-field-guide/commit/87082d1f8b7dee84feda7dc1ef5d705838728f88

**Comment by timbellnz** [comment]
Updated text in chapter, added some examples, inserted missing images, fixed links

commit a8b59d5fd59f86ca0a8936979ff43b321d3d7440
