### ISSUE TITLE
Encryption chapter: Add curiosity about tractability in brute force attacks section

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#143]
A good topic to cover when talking about guessing keys. Can link to the tractability chapter for keen students.

perhaps you can do this Tim? You're good at writing about this kind of thing :-)

**Comment by Heidirose** [comment]
@timbellnz I noticed a bit later in the RSA section that we have an existing box about intractability, although it uses the factoring problem. It is also a little bit long. What I'm thinking is that it'd be awesome if we introduced tractability in the caesar cipher section (when we talk about key lengths), and then expand on it a bit in the RSA section. So effectively two curiosity boxes on tractability. Thoughts?

Text in guide
===========

curiosity}

**Easy vs Difficult problems in Computer Science**

If you were asked to multiply the following two big prime numbers, you might find it a bit tiring to do by hand (although it is definitely doable!), but could get an answer in milliseconds by putting it in the big numbers calculator! (included just below this box).


```
97394932817749829874327374574392098938789384897239489848732984239898983986969870902045828438234520989483483889389687489677903899
```

```
34983724732345498523673948934032028984850938689489896586772739002430884920489508348988329829389860884285043580020020020348508591
```

If on the other hand you were asked what two prime numbers were multiplied to get the following big number, you’d have a lot more trouble!  (If you do find the answer, let us know! We’d be very interested to hear about it!)

```
3944604857329435839271430640488525351249090163937027434471421629606310815805347209533599007494460218504338388671352356418243687636083829002413783556850951365164889819793107893590524915235738706932817035504589460835204107542076784924507795112716034134062407
```

So why is it that despite these two problems being similar, one of them is “easy” and the other one is “hard”? Well, it comes down to the algorithms we have to solve each of the problems.
You have probably done long multiplication in school by making one line for each digit in the second number and then adding all the rows together. We can analyse the speed of this algorithm, much like we did in the algorithms chapter for sorting and searching.
Assuming that each number has the same number of digits, which we will call n (“Number of digits”), we need to write n rows. For each of those n rows, we will need to do around n multiplications. That gives us n*n little multiplications. We need to add the n rows together at the end as well, but that doesn’t take long so lets ignore that part. We have determined that the number of small multiplications needed to multiply two big numbers is approximately the square of the number of digits. So for two numbers with 1000 digits, that’s 1,000,000 little multiplication operations. A computer can do that in less than a second! If you know about Big-O notation, this is a O(n^2) algorithm, where n is the number of digits! Note that some slightly better algorithms have been designed, but this estimate is good enough for our purposes.

For the second problem, we’d need an algorithm that could find the two numbers that were multiplied together. You might initially say, why can’t we just reverse the multiplication? The reverse of multiplication is division, so can’t we just divide to get the two numbers?
It’s a good idea, but it won’t work. For division we need to know the big number, and one of the small numbers we want to divide into it, and that will give us the other small number. But in this case, we *only* know the big number. So it isn’t a straightforward long division problem at all!
It turns out that there is no known good algorithm to solve the problem. One way is to just try every number that is less than the number (well, we only need to go up to the square root, but that doesn’t help much!) There is still billions of billions of billions of numbers we need to check. Even a computer that could check 1 billion possibilities a second isn’t going to help us much with this! If you know about Big-O notation, this is an O(10^n) algorithm, where n is the number of digits -- even small numbers of digits are just too much to deal with!
There are slightly better solutions, but none of them shave off enough time to actually be useful for problems of the size of the one above!

The chapter on Complexity and Tractability looks at more computer science problems which are surprisingly challenging to solve. If you found this stuff interesting, do read about Complexity and Tractability when you are finished here!

{curiosity end}

**Comment by Heidirose** [comment]
Note that I'm also putting the details of RSA (factors and primes) into a curiosity box, so that the main text focuses primarily on public key system concepts, and the curiosity boxes are an extra for those interested in the mathy details (I'm going to do that particular bit, as I already have the text for it).

**Comment by timbellnz** [comment]
Written a curiosity box (for the Caesar section), and adapted the text above for a curiosity in the RSA section.
commit 1e4842784259d3379a944a4e04628493b0b0ca4d
