### ISSUE TITLE
License System

### ISSUE THREAD

**Issue by Jamesernator** [uccser/cs-field-guide#145]
We need a proper system for licensing anything (modules, code fragments, images, text, etc), my suggestion is anywhere we license something we also add a file (like a .license.json or something) that contains info that could be used by a license listing generator (for example we could list a summary by owner and have an openable section for all such resources used)

For example a sample license might look like this:
```json
# File included in same location as image
{
    "author": "Randall Munroe",
    "type": "image",
    "original": "http://imgs.xkcd.com/comics/np_complete.png",
    "fragment": "false",
    "modified": "false",
    "usage": "Part of Chapter Complexity and Tractibility",
    "ourCopy": "./xkcd-np-complete-comic.png",
    "licenseURL": "http://xkcd.com/license.html"
}
```

from which we could then generate some page like:

---

##### Randal Monroe
- "NP Complete"
    - Usage: "Part of Chapter Complexity and Tractability"
    - Modified: "False"
    - License: "http://xkcd.com/license.html"

etc...

---

I'd be happy to write the generator, but would everyone be on board with using a system like this? (e.g. you'd just throw the file where you have the copyrighted material and the parser finds all .license.json files in the entire field guide and generates a license page).

Also what fields should be included in every license.json file and what additional ones should be considered?

**Comment by JackMorganNZ** [comment]
There is also a prototype of managing licenses but Jordan and I have planned to extend the current system. It's something I plan to do when I return, as it does not need to be implemented over Christmas.

**Comment by Heidirose** [comment]
Hi Jack,

Thankyou for your response.

It would be helpful if you told us what we should be doing with licence files in the mean time, which will make it easy as possible for you to move them into the new system once it is written.

Cheers!
Heidi

**Comment by JackMorganNZ** [comment]
The temporary location of details is the `permissions.conf` file.

**Comment by Heidirose** [comment]
Closed as Jack already has plans to do something else :-)
