### ISSUE TITLE
Consider removing the coding introduction chapter

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#147]
From an international perspective, that chapter is not contributing to the guide. The only content in it currently is teacher notes and stuff related to NCEA, which should instead be in the curriculum section.

@timbellnz do you mind if I just remove it altogether?

**Comment by timbellnz** [comment]
The idea that there are three kinds of coding is a generic concept (and appears in other books), but the teacher specific material could be removed. I think it's useful to tackle the ambiguity of "coding" somewhere. The alternative is to mention it in each chapter, but that would be repetitive.

**Comment by Heidirose** [comment]
That's a good idea. Currently that chapter isn't really doing that, and effectively needs a complete rewrite (although will be a short chapter). Are you able to do that, given that you are a guru at coding topics?

We could also bring up a couple of other ideas in curiosity boxes, such as entropy and information theory in general :-)

**Comment by Heidirose** [comment]
Closing this and making a new issue for rewriting the chapter.
