### ISSUE TITLE
Rewrite the coding introduction chapter

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#148]
Related to the discussion on #147 , we are going to rewrite this chapter so that it provides a meaningful introduction to coding.

A few initial thoughts I have...
- All the text about NCEA (i.e. everything except for the last section) should be removed - it's already in the curriculum guides.
- We should provide a couple of interesting curiosity boxes on stuff like entropy and information theory.
- We should clearly define what coding is and how it differs from data representation (ironically called encoding...).
- Perhaps briefly introduce the three (or four if you count hashing as seperate from encryption) coding topics, and talk about why they are part of the general idea of coding?

**Comment by timbellnz** [comment]
The chapter has been updated, extra information about entropy added, cartoon of Shannon (from Unplugged) added, some material converted to a curiosity, NCEA specific material removed.

commit 0ef83f667a4c194087a4ae01dce085520b71c6cc

Only a little is mentioned on the relationship with data representation; the distinction is more relevant to NCEA, where students must cover both topics. In principle, even simple representations are a form of coding (e.g. binary is Elias' beta code).

The following has been removed, but may be useful in the NCEA curriculum guide:

---
The 2.44 standard requires that students show a basic understanding of all three kinds of coding to get the achieved level, but only one of the three needs to be investigated to the excellence level. The standard is focussed on practical applications of coding, which is a valuable motivator: what would go wrong in a student's world if coding didn't happen (mp3 players would store very few songs; online banking wouldn't be possible; and data on computers couldn't be trusted to stay accurate).

Despite the focus on practical applications, we recommend that you get students to investigate a basic algorithm for each of the topics, and this is included in the three following chapters. It's a bit more than the standard requires, but it is ideal that students will go away from this understanding what each of these three topics is about, and knowing how the algorithms work for some simple examples will help them to see the importance of coding. Simple examples are:
- Error control coding: The Parity Trick (or ISBN/ Food barcodes)
- Encryption: Caesar Cipher (not a good encryption method, but is suitable for explaining terminology)
- Compression: Run length encoding (a simple compression method that was used for Fax machines), Ziv-Lempel compression (a method that is fairly easy to understand in principle, and is widely used for zip files, GIF images, and more).

The Merit and Excellence levels will require a discussion and evaluation of a widely used technology. Ideas are provided in the chapters; examples are:
- Error control coding: ISBN book numbers, food barcodes, or possibly RAID disks
- Encryption: the HTTPS protocol or the PGP encryption system are easy to access.
- Compression: Commonly used methods are JPEG (for photos), MP3 and AAC (for audio), zip and rar (for general files), and GIF and PNG (for simple images). Issues that can be investigated include lossy versus lossless compression, and the tradeoffs between them. Students will probably do this either using lossless algorithms that are used for file compression, or lossy algorithms that are used for image and sound compression.
---

**Comment by timbellnz** [comment]
Consider merging the removed NCEA material from https://github.com/uccser/cs-field-guide/issues/148 into the NCEA coding guide, and make sure the guide is clear how coding differs from data representation for the purposes of assessment.

**Comment by eAlasdair** [comment]
closed for inactivity, if new information is provided a new issue can be created
