### ISSUE TITLE
Another example for preventing errors heuristic?

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#150]
@timbellnz we just found a rather nice example of the "prevent errors" heuristic being violated. Want to include an image of this in the guide?

![malformed-expression](https://cloud.githubusercontent.com/assets/7854960/11882902/4becbee4-a574-11e5-9f71-9eb18fb8661c.png)

The error was because I had typed digits that were not 1's and 0's -- something I should not have been allowed to do. It's cool because it has a good computer sciency theme to it. It happened because a few days ago I was using the calculator program to do something in binary, and then today when I opened it, it was still in that mode but I didn't notice. Not only is it an example of "prevent errors", it is also an example of a useless error messages :-)

**Comment by timbellnz** [comment]
I've added the calculator, and also got carried away and added an ATM example.

commit number 1d8c17fa637c2956497bd3f5d2b937b2671270be
