### ISSUE TITLE
Product Suggestion- GitHub Classroom Extension for VS Code

### ISSUE THREAD

**Issue by fubaduba** [uccser/cs-field-guide#1515]
Hi,
I'm the PM owner for the [Visual Studio Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) and [GitHub Classroom extension](https://marketplace.visualstudio.com/items?itemName=GitHub.classroom) in Visual Studio Code.
The cs-field-guide is a resource for getting students started with computer science, and that is exactly what we're trying to enable with these extensions as well. I would love to connect with the open source maintainers of this project to understand what their current pain-points are with tooling and getting students started.
Thanks,
Filisha Shah 
fishah@microsoft.com

**Comment by JackMorganNZ** [comment]
Hi Filisha,

We are currently working on adding more content, and ensuring that content is translatable. The extensions you manage for VS Code don't seem useful with the approach that the CS Field Guide uses for teaching Computer Science. There is very little programming, as this is the tool used for the concepts taught in our online textbook. We work on this project in our spare time, and don't have any quotas or metrics we need to meet, as it's a free resource we share. We don't directly work with students, we provide this to educators who use it with students how they wish.

I'll close this issue (as there is nothing to currently fix), but feel free to reply with any specific ways you think your extensions could assist us.

Thanks,

Jack
Project Manager
