### ISSUE TITLE
Tim needs to adapt his fourier spreadsheet for compression section on JPEG

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#152]
Based on a comment in the compression chapter...

I think it would be really good to include this, given that students are expected to do something reasonably deep for coding at the excellence level.

The suggested links in the comment are of little use, because they require downloading 3rd party software.

Either that, or we need to make our own interactive. At this stage, I don't think we have enough programming time to make an interactive for it.

**Comment by timbellnz** [comment]
Done. It will need checking in context later when I check the whole chapter, but the material is all there now. I have included the links to Wolfram as an alternative; it's widely used and educationally focussed, even though schools may have trouble installing the plugin.

**Comment by timbellnz** [comment]
commit a68f6ff0b04915397e8eab62057b720dcc5340e6
