### ISSUE TITLE
Compression teacher notes to put in curriculum guide

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#155]
{teacher}

This section provides enough information for students to work up the the excellence level for coding. The requirements are:
- Merit: discussing how a widely used technology is enabled by one or more of compression coding, error control coding, and encryption
- Excellence: evaluating a widely used system for compression coding, error control coding, or encryption

Student reports will revolve around the benefits that enable a widely used technology (such as compressed file sizes making it feasible to view photographs interactively online) for merit, and comparing (evaluating) the size and quality of images before and after they have been compressed.

This section ties in well with AS91370 (2.43) work on web design. For the 2.43 standard the focus in compression is using a format that looks suitable and has a small file size for the particular images being used on a web site being designed. For the 2.44 standard (covered here) we look a little at _how_ the compression works, and evaluate it on a variety of images including extreme cases, to draw general conclusions about the performance of various compression methods. Although the work is complementary, understanding one will obviously help students with the other.

[An ebook to support AS91370 (2.43)](https://drive.google.com/folderview?id=0BxTv4DHp39Q-UEFoWDJiSWZEQ3c&usp=sharing) has been published by Jennifer Gottschalk.

{teacher end}

**Comment by eAlasdair** [comment]
Closed for being out of date
