### ISSUE TITLE
Tim needs to check over Run Length Encoding section of compression

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#156]
@timbellnz 
I have refactored it considerably. The goals were
 - Remove NCEA specific stuff
 - Ensure example could be followed even if a teacher not present
 - Better structured with headings.
 - Redispersed panels, as many were not in optimal places, and too many were at end.

Thoughts? Happy with it? Feel free to make further changes! I think a couple of images, e.g. one of a fax machine would be a nice addition too.

Relevant commit: https://github.com/uccser/cs-field-guide/commit/e29a4daddc3a7ec19d0cfbe83d9829ae3f01dacb

**Comment by timbellnz** [comment]
Added explanation of how it fits in to history/teaching; fine tuning of
wording; extra information on how lossless methods can expand a file.

Looks good to me.

commit a29c90e097440d697ca08c4ada38610b642ca2e6
