### ISSUE TITLE
Make a parity trick sandbox

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#158]
For students to experiement with the parity trick, without needing to have a physical set of cards in front of them.

**Comment by JackMorganNZ** [comment]
A reminder for @Heidirose to add a diagram

**Comment by JackMorganNZ** [comment]
I've created the first version of the parity trick sandbox interactive. @Heidirose can you checkout the interactive, you will need to switch to the `parity-sandbox` branch (I forgot to put `interactive` at the start of the branch! Doh!) and open the file at `interactives/parity-sandbox/index.html`.

Let me know your thoughts about it. Some possible ideas to add are:

- Add clear button to turn all cards white.
- Add random data button that fills in cards with random values (not parity row).
- Add highlight showing parity error, however I feel like this stops opportunities for learning how it works.

**Comment by JackMorganNZ** [comment]
This has been completed in the new parity interactive.
