### ISSUE TITLE
Move RSA Key Generator interactive

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#16]
Move interactive from Encryption Coding chapter
```
<div class="col-xs-12 col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-heading">RSA Key Generator</div>
<div class="panel-body">
    <div class="row">
        <form id="modeSelect" class="form-horizontal" role="form">
            <div class="form-group">
                <div class="col-xs-12 text-center">
                <input type="button" id="generate" onclick="generate_new_keys()" value="Generate New Keys" class="btn btn-primary">
                </div>
            </div>
            <div class="form-group">
                <label for="pub_key" class="col-xs-3 control-label text-right">Public Key</label>
                <div class="col-xs-8">
                    <textarea id="pub_key" class="form-control" rows="1" readonly="true"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="priv_key" class="col-xs-3 control-label text-right">Private Key</label>
                <div class="col-xs-8">
                    <textarea id="priv_key" class="form-control" rows="1" readonly="true"></textarea>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>
<div class="clearfix visible-xs-block"></div>
```

**Comment by Heidirose** [comment]
Work on this one alongside the encrypter/ decrypter

https://github.com/uccser/cs-field-guide/issues/17

**Comment by JackMorganNZ** [comment]
This interactive was never finished and added to the text. I'll implement this for 2.0.1.

**Comment by Heidirose** [comment]
Just a note for this one: Be sure that it goes along with the encrypter/ decrypter that is also in the chapter. I have an activity that uses them both (assessment guide)

Be careful about key length. The length I have in the old version seems about right to ensure that it doesn't run too slowly on older computers.

**Comment by JackMorganNZ** [comment]
I plan on using this library, which creates 512bit keys in around 30ms on my desktop, so on slow computers I would estimate it would take 100-300ms. I think this is an acceptable time, I can disable the button too to stop multiple presses from occuring at once. Does that suit? Or do you need 1024 bit?

I can't find how large key size was in the [old generator](http://www.csfieldguide.org.nz/releases/1.9.9/_static/interactives/en/en-interactives.js).

**Comment by Heidirose** [comment]
The key in the old interactive was considerably smaller (50 bits according to that code). Are you certain that the 512 bit key will work okay with encrypting and decrypting as well?

Also, if you use libraries for the encrypter/ decrypter, can you ensure that the encrypter/ decrypter is not adding anything fancy such as padding? (We don't want this for the initial explanations, the students should be able to see the effects of *not* using padding, e.g. that two messages with the same plaintext will have the same ciphertext).

**Comment by Heidirose** [comment]
If we actually could get away with 1024 bit, then that would be even better. Large key sizes are desirable in that they mean a far larger block size.

And one more thought on the padding: It would be super awesome if we had two interactives -- one which does not use padding, and one which does, to show students the importance of using it for RSA (as of course, a big part of encryption is using techniques correctly). And on that note, we need to have some kind of disclaimer that the algorithms used by our interactives should NOT be used for any real world purposes (hopefully that goes without saying though...).

**Comment by JackMorganNZ** [comment]
Just realised I didn't link to the library, this is what I plan to use which gives you a demo: http://travistidwell.com/jsencrypt/demo/index.html

**Comment by JackMorganNZ** [comment]
I'll add RSA interactives for generation, encrypting, and decrypting following the [text here](https://github.com/uccser/cs-field-guide/blame/master/text/en/chapters/coding-encryption.md#L509). We can then schedule a proper check over from an author at a later time.
