### ISSUE TITLE
Colon in headings prevents them being numbered

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#164]
For example, the second section in Software Engineering was "## Analysis: What do we build?" was unnumbered. I've worked around by replacing the colon with an em-dash. Escaping the colon or using ASCII doesn't seem to fix it. It would be nice to have colons allowed in headings if possible.

**Comment by JackMorganNZ** [comment]
Cheers, Heidi had logged this but I had closed it as I couldn't see the issue. I'll get this sorted ASAP.
