### ISSUE TITLE
Hyperlinks don't render properly if they contain parentheses

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#165]
eg.  in Software Engineering chapter:
[Scrum](http://en.wikipedia.org/wiki/Scrum_(development))

The ")" doesn't appear at the end of the URL in the link.

**Comment by JackMorganNZ** [comment]
Thanks for spotting this! It's most likely due to our regular expression matching, I'll sort this out.

**Comment by timbellnz** [comment]
In case the source needs changing... the same chapter has the problem in this link too:
[Wikipedia - Abstraction](http://en.wikipedia.org/wiki/Abstraction_(computer_science)

**Comment by JackMorganNZ** [comment]
@timbellnz I thought about changing the regex to be greedy, but then it wouldn't have any decent stopping point! I could also only assume the close bracket is the last character, but what might be a smarter option is to escape any closing brackets within the link.

Thoughts?

**Comment by timbellnz** [comment]
@JackMorganNZ Escaping within the link would be fine; they are fairly rare.
