### ISSUE TITLE
Check introduction section

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#166]
Update the section to reflect changes in the guide, check links etc.

**Comment by JackMorganNZ** [comment]
@timbellnz I propose we redo the interactive in the introduction section with one calculator. The text above could say enter 34 + 57 in the calculator, then try 74 - 39. The calculator can switch between useful and not useful interfaces on correct answers. Thoughts?

**Comment by timbellnz** [comment]
I think it's best to keep the good and bad interfaces separate, so students (and demonstrators) can freely switch between them. Paradoxically, we need a good interface design to make it easy to access the bad interface.

**Comment by timbellnz** [comment]
Material in introduction updated to match new format and content of the guide, and external links/recommendations brought up to date
commit 156cd2ba28032b7e4f8c659a4d787c902aac42e3
