### ISSUE TITLE
transfer old glossary entries

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#168]
The definitions in the old glossary (was http://csfieldguide.org.nz/appendices/Glossary.html in the 2015 guide) need to be transferred and linked into the new version.

**Comment by JackMorganNZ** [comment]
I'll be merging new glossary changes later today, best to wait until then before writing glossary entries.

**Comment by JackMorganNZ** [comment]
Any update on the progress of this @timbellnz?

**Comment by timbellnz** [comment]
Not yet - it's a backburner job. If someone is available to pick it up, that's fine.

**Comment by JackMorganNZ** [comment]
@timbellnz I've removed all glossary entries that have been already transferred.

**Comment by eAlasdair** [comment]
outdated
