### ISSUE TITLE
files in teacher edition not copying

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#172]
e.g in HCI chapter, reference to:
file:///Users/tcb11/GitHub/cs-field-guide/output/en/teacher/files/HCI-posters.pdf
file isn't there

**Comment by timbellnz** [comment]
Had the same problem in the compression chapter with the link to output/en/teacher/file/Adding-Sine-Waves.xls

**Comment by JackMorganNZ** [comment]
I presume it's because the folder name should be `files` not `file` from the URL you posted. We might need to consider changing plural folder names to singular. Thoughts @timbellnz?

**Comment by timbellnz** [comment]
Fixed :-)

I think the plural folder name is correct. It was just me jumping to the conclusion that the old bug was causing it.
