### ISSUE TITLE
Formal languages - add Regex interactive

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#173]
The interactive RegexDic.html is missing from the formal languages chapter (there's a note mentioning it). The alternative isn't ideal for classroom use; we need a temporary link to the old interactive, assuming that it's awaiting an update. This version works ok:
http://csfieldguide.org.nz/_static/widgets/FL/FL-Regex/RegexDic.html

**Comment by timbellnz** [comment]
Actually, all the interactives need hooking in, and also the figures need to be put there.

**Comment by JackMorganNZ** [comment]
In regards to the interactive to replace the [old regex interactive](http://www.csfieldguide.org.nz/releases/1.9.9/_static/widgets/FL/FL-Regex/RegexDic.html), are the Wikipedia and Aonaware features required? Or is a large list of words fine?

**Comment by timbellnz** [comment]
Just a large list of (public domain) words is fine.

**Comment by JackMorganNZ** [comment]
Awesome, I should be able to create this fairly quickly then.

**Comment by JackMorganNZ** [comment]
This issue will replace #42 as it has more information.
