### ISSUE TITLE
Plane turbulence interactive thumbnail is of an error

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#1745]
On the [interactives page](https://www.csfieldguide.org.nz/en/interactives/), the thumbnail for the plane turbulence interactive displays an error. Same goes for the chapter the interactive is rendered in ([HCI](https://www.csfieldguide.org.nz/en/chapters/human-computer-interaction/fitts-law/#pointing-in-non-ideal-environments))

![image](https://user-images.githubusercontent.com/16066822/166847530-77e3d640-0613-4ca9-9803-d9371670e890.png)

**Comment by JackMorganNZ** [comment]
This has been fixed in 2bdf8e71907053f7a8630a65805aa0d5da686137, however there hasn't been a release since then. Thanks for reminding me to do one!
