### ISSUE TITLE
Large MathJax equation blocks are not responsive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#176]
Large sections of math flow outside of the page body. 

A responsive solution is required, most likely either resizing the equation to fix, adding a scroll bar, or adding line breaks.

**Comment by pkra** [comment]
This might be helpful http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking

**Comment by JackMorganNZ** [comment]
Thanks @pkra. I read through several threads yesterday regarding this, and saw your help/work in some of them.

You may be able to assist in something else. We wish to have a local copy of MathJax stored in our repo, so when it creates HTML output with all the JS/CSS files it can display math offline (we were using CDN before). 

The full installation of MathJax is quite large in both size and number of files. We have followed an older guide to trim the files down (removing docs, etc) but we still don't know what we actually *need* for our project. Do you know of any docs/guides that talk through the different configurations/setups of MathJax? For example, I don't know which font is best (or do I need multiple for compatibility?).

We haven't had a proper search yet, but thought I should ask since you've popped up on this repo. Any help is appreciated!

**Comment by pkra** [comment]
>  We have followed an older guide to trim the files down 

Have you seen https://github.com/mathjax/MathJax-grunt-cleaner? It hasn't been updated for 2.6.0 yet though.

> we still don't know what we actually need for our project. 

Hard to tell as an outsider. Usually one input, one output, one font.

> For example, I don't know which font is best (or do I need multiple for compatibility?

Most people are fine with any choice. See also http://docs.mathjax.org/en/latest/font-support.html#character-fallbacks
