### ISSUE TITLE
Computer Graphics Chapter

### ISSUE THREAD

**Issue by npnzsue** [uccser/cs-field-guide#1836]
## Description

Clearly and concisely describe the issue or suggestion here:

The 3D section of the Graphics Transformations doesn't load the interactives for us.
We have tried in Chrome and Edge.

### Checklist

*Change the space in the box to an `x` for those you have completed. You can also fill these out after creating the issue.*

- [ ] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] The platform(s)/software you are encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Thanks @npnzsue, will be tracking fixing this on #1837.
