### ISSUE TITLE
3D Transform examples do not load

### ISSUE THREAD

**Issue by MrConorAE** [uccser/cs-field-guide#1837]
## Description

The 3D transformation examples on the "Graphics Transformations" page do not load. As a result, you can't see/use/try the examples there.

This log output (from the browser console) may be relevant:
```
Uncaught TypeError: c.uniforms.tCube is undefined
    init scene-editor.js:97515
    [582]< scene-editor.js:97409
    o scene-editor.js:1
    r scene-editor.js:1
    <anonymous> scene-editor.js:1
scene-editor.js:97515:2
    init scene-editor.js:97515
    [582]< scene-editor.js:97409
    o scene-editor.js:1
    r scene-editor.js:1
    <anonymous> scene-editor.js:1
```

### To Reproduce
1. [Visit this page on the CS Field Guide](https://www.csfieldguide.org.nz/en/chapters/computer-graphics/graphics-transformations/#3d-transforms)
2. Select any of the "3D Transforms" examples, which open in a new tab.

### Expected Behavior
The linked examples load and the examples can be seen.

### Actual Behavior
The examples do not load - it's only a blank page that can't be interacted with.

### Platforms
- Firefox 102.0 (snap) / Ubuntu 22.04 - doesn't work
- Chrome 102.0.5005 / Windows 10 - doesn't work

### Checklist

*Change the space in the box to an `x` for those you have completed. You can also fill these out after creating the issue.*

- [X] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number). - No existing issues

If this is a code related issue, please include the following in your description:

- [X] Steps to reproduce the behavior
- [X] The platform(s)/software you are encountering the issue on
- [X] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Thanks @MrConorAE, I should have time to look into this later today or tomorrow. Thanks for the detailed report.

**Comment by JackMorganNZ** [comment]
Update: I've been working on this today and may take me some time since our previous `three.js` developer has moved on. Don't have an ETA on a fix sorry.

**Comment by JackMorganNZ** [comment]
Have fixed this issue, will try to have it deployed to the production website by this afternoon.

**Comment by MrConorAE** [comment]
Perfect, thank you so much!

**Comment by JackMorganNZ** [comment]
The fix has been deployed to the website and is now avaiable at: https://www.csfieldguide.org.nz/en/chapters/computer-graphics/graphics-transformations/#3d-transforms

Let me know if you have any other issues.
