### ISSUE TITLE
RSA interactives -- make sure that interface bug not transferred to new guide

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#190]
When you hover over the key interactive in the old guide, it shows a symbol that implies you cannot copy paste. Make sure the new version does not do this.

**Comment by JackMorganNZ** [comment]
@Heidirose Can you please post a link to the old interactive you are referencing?

**Comment by JackMorganNZ** [comment]
This was solved by recreating the interactives.
