### ISSUE TITLE
FSA page Trainsylvania activity refers to City Mall and Suburbopolis

### ISSUE THREAD

**Issue by waimea-cpy** [uccser/cs-field-guide#1902]
The [FSA page](https://www.csfieldguide.org.nz/en/chapters/formal-languages/finite-state-automata/) Trainsylvania activity refers to **City Mall** as the start point, and **Suburbopolis** as the target. These places don't exist on the map (guessing they were from a previous version)

**Comment by JackMorganNZ** [comment]
Fixed in a018950e69dd03a41eeca44ade10a6cf050add1d

Thanks Steve for pointing that out, the fix will be pushed to the production website soon.
