### ISSUE TITLE
[Bug]: A few issues on the Computer Security chapter main page

### ISSUE THREAD

**Issue by eon-rgb** [uccser/cs-field-guide#1913]
### Description of the bug

There's a spelling mistake in the following line: "For example, 2% of internet traffic is immediately recongnisable as an attack and gets blocked right away". recongnisable should be recognizable. The second URL linked under "(some current statistics are available here, here and here)", where "here" is the hyperlink leads to a page that doesn't contain statistics.

### Steps To Reproduce

1. Click on 'View Chapters"
2. Scroll down to Chapter 10: Computer Security
3. Scroll down on the page until you notice the spelling mistake
4. Click on the second "here" and you will be directed to Akamai's Secure Internet Access product page containing no statistics about attacks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JackMorganNZ** [comment]
Thanks @eon-rgb for pointing out this issue. I've pushed a fix that will be released to the production website soon.
