### ISSUE TITLE
Syntax cannot be used within glossary definitions

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#192]
In this raw text `{glossary-definition term="slope" definition="This is a way of expressing the angle or gradient of a line. The slope is simply how far up the line goes for every unit we move to the right. For example, if we have a line with a slope of 2, then after moving 3 units to the right, it will have gone up 6 units. A line with a slope of 0 is horizontal.
Normally the slope of a line is represented using the symbol
{math}m{math end}."}` the `m` at the end is missing as the glossary definition regex stops matching at soon as a end curly bracket is found. This is due to how arguments are parsed in the field guide.

To correctly detect matching brackets, we would need to switch away from regular expressions, so the simpler solution for the moment is to not use `{math}` tags within other tags.

Thoughts @timbellnz

**Comment by timbellnz** [comment]
I think we can leave that as a long-term issue. Eventually it may become important, but in this case (at least) we can just use italics (*m*).

Another solution might involve escaping the math? A related problem likely arises with inverted commas in the definitions. But this can wait for a later release.

**Comment by JackMorganNZ** [comment]
It turns out no syntax can be used in the glossary definition (for example, italics). I've thought of a solution for math and for basic markdown (like italics).

1. HTML for math spans/blocks (possibly all HTML) must use single quotes to it's not matched by argument parser (which searches for double quotes).
2. The glossary page must load MathJax to view content.
3. The contents of the definition must be parsed with the Markdown parser, in the same way panels are processed.

I'll implement this later this week.
