### ISSUE TITLE
Add custom text to interactive buttons in Computer Graphics chapter

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#193]
Add custom texts to each interactive button (HTML starts with `{button ....`) to describe the interactive.

**Comment by timbellnz** [comment]
Custom text added around all the buttons.

**Comment by timbellnz** [comment]
There are some interactives at the start that didn't have buttons:

> {include interactive computer-graphics-box-translation}
> {include interactive computer-graphics-box-rotation}
And the following interactive 4 times (with different parameters):
> {include interactive computer-graphics-arrow parameters=

Each has been replaced with a button to the old field guide location, as for the other ones.

**Comment by timbellnz** [comment]
Issue fixed
commit 099fb86fad205baf01890f6506872920573c0103
