### ISSUE TITLE
WebGL help page needed

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#199]
In the graphics section there is a reference to a page that explains tricks for getting WebGL to work:
> there is [information here about how to get it going](appendices/webgl_help.html).

The linked page needs to be copied across from the old project and formatted.

**Comment by JackMorganNZ** [comment]
Existing page of notes is here: http://www.csfieldguide.org.nz/releases/1.9.9/appendices/Interactives.html

Notes need to be copied/updated to `text/en/further-information/interactives.md` which is currently only on the `guide-content` branch.

**Comment by hayleyavw** [comment]
@JackMorganNZ confirmng that instead of only covering WebGL, we want an info page for all interactives, with a section for WebGL?

**Comment by JackMorganNZ** [comment]
Yep, all interactives will be more effective, and it can go in the text file here: `text/en/further-information/interactives.md`

**Comment by hayleyavw** [comment]
@JackMorganNZ I moved the text for WebGL from the old webpage, if you could proofread it that would fantastic :smile:

**Comment by hayleyavw** [comment]
*ping* @JackMorganNZ you did some work on this right? what needs to be done before we can close this issue?

**Comment by JackMorganNZ** [comment]
I did commit it (just forgot to tag the issue), I'll merge it in now.
