### ISSUE TITLE
Curriculum guide section links not working

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#205]
The section headings in the right margin of the NCEA guides don't work; they seem to have the word "section-" added, which gives the wrong link.

For example, the TSP guide (curriculum-guides/ncea/assessment-guide-level-3-complexity-tractability-TSP.html) links sections with the following style of name:
curriculum-guides/ncea/assessment-guide-level-3-complexity-tractability-TSP.html#writing-your-report

But the links in the margin go to
curriculum-guides/ncea/assessment-guide-level-3-complexity-tractability-TSP.html#section-writing-your-report

**Comment by JackMorganNZ** [comment]
The `section-` is intentional, as the heading (and it's text) should be surrounded by a div with id `section-`... but it doesn't seem to be working as intended. I will look into getting this working, and also the usability side of having separate IDs for both the section and heading.
