### ISSUE TITLE
Update introduction to teacher guide

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#213]
In the about page, the link to the teacher guide takes you to the following text, which needs updating to reflect the new structure. Where should this text be edited, and does it appear in the student guide as well? I can do the editing once I know the structure.

_A teacher's guide is available (currently aimed primarily for New Zealand teachers teaching NCEA). Read the About section for more details to access this.

This guide features interactive activities within some of the chapters. These should work with any modern browser updated in the last year, but we are continually expanding the compatibility of these. This guide is open source and available on GitHub._

**Comment by JackMorganNZ** [comment]
So you are saying the section about accessing the teacher guide on the homepage should not appear on the teacher version? This makes sense, are should be solved (eventually) by #208.

**Comment by timbellnz** [comment]
Correct, although it would be good to have something there since it's a landing page. Feel free to roll this into #208 and I can work on the text once it has a final resting place.

**Comment by JackMorganNZ** [comment]
#208 won't be solved anytime soon (most likely when the generator is extracted), but the text for the homepage can be edited in the `generator/html-templates.conf` file. It's between the tags `{website_homepage_content}` and `{website_homepage_content end}`. The about page can be edited by editing the file `text/en/about.md`.

I'll close this issue as it seems to answer your question. But it would be worth checking the files that prompted this question to check if any of the text is required to be changed (and create a new issue for it).

**Comment by JackMorganNZ** [comment]
I've implemented a solution for #208 when working on #364 , and now the text can be configured easily for each language. It has not been pushed to `develop` yet (and may be a few weeks until this happens) but we can think about changing this text again now.

@timbellnz Did you want to alter the text on the homepage (or any other pages) in relation to this issue?
