### ISSUE TITLE
Redirect old links to 2.0 content

### ISSUE THREAD

**Issue by samjarman** [uccser/cs-field-guide#217]
We can do this with Apache and a 301 redirect, that way, Google learns too! 

Some (potentially) useful links: 

http://superuser.com/questions/155139/htaccess-301-redirect-with-regular-expressions

https://docs.webfaction.com/software/static.html#redirect-a-domain-with-a-static-cgi-php-app

This stuff, in my experience, is always a bit niggly. 

As for what exactly to redirect, we can redirect old chapters to new, as they follow a similar format. The change from Camel Case to dash-case might be hard though with a regex. I'll leave it to the implementer to decide though.

**Comment by courtneycb** [comment]
Resolved in #872
