### ISSUE TITLE
Rewrite text to not use missing resource

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#218]
The Dynalab resources appear to have been taken offline. These are within the `formal-languages.md` file, search for `http://www.cs.montana.edu/%7Edynalab/`. The only page I could find related is https://www.cs.montana.edu/webworks/webworks-home/projects/dynalab-windows/dynalab-description.html.

**Comment by JackMorganNZ** [comment]
The web archive has a snapshot available here: https://web.archive.org/web/20100626064755/http://www.cs.montana.edu/~dynalab/

**Comment by timbellnz** [comment]
I've removed it; Dynalab is getting a bit stale and is Java based, so problematic to use.

commit b93aa45fcbe2fd95920aa8ce96b46a70774961d0
