### ISSUE TITLE
Consider redesigning the Braille diagrams

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#220]
The ones that show how many combinations there are with 2 dots and 3 dots are potentially misleading in that they group all the patterns into rectangle shapes (much like actual Braille). The lines are numbered, although I don't think this is obvious enough.

We need to draw it so that it is really really obvious that each line is independent of the others. I'll come up with a suggestion of how to go about this at some point.

Any other thoughts? @timbellnz @JackMorganNZ

**Comment by Heidirose** [comment]
@timbellnz , still want to do this or shall I assign it to somebody else?

**Comment by eAlasdair** [comment]
This is the current implementation, @Heidirose @timbellnz @JackMorganNZ do you still think it should be changed?

I could make the line between them thicker, and/or make it vertical

![image](https://user-images.githubusercontent.com/25916475/56780408-3f87dc80-6833-11e9-80ea-ab1c57050ffa.png)

**Comment by eAlasdair** [comment]
Consider making an interactive - There are x dots, find all the possible combinations

**Comment by eAlasdair** [comment]
Combining with #219
