### ISSUE TITLE
Process old archived links

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#222]
The following links have not been valid for some time, and `web.archive.org` links were used instead. Alternative links need to be found, or the text rewritten. 
- `coding-compression.md` - line 502
- `computer-vision.md` - line 91
- `formal-languages.md` - line 1355
- `formal-languages.md` - line 1437
- `contributors.md` - line 46 (this link could be removed and leave the text as is)

**Comment by eAlasdair** [comment]
Closed, Linkie
