### ISSUE TITLE
Second caesar cipher interactive in encryption chapter conflicts with first one

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#224]
This either needs to be run in an iframe if two are needed, or removed. The text around the interactive should reflect this change.

@timbellnz Do you want two copies? I can switch the operating mode if yes.

**Comment by timbellnz** [comment]
It would be good to have two copies, so it's on hand when it's needed in each place.

**Comment by Heidirose** [comment]
I'll have a look at this sometime soon. I'm still working on that chapter

**Comment by Heidirose** [comment]
From memory though, it is deliberate to have it twice :)

**Comment by JackMorganNZ** [comment]
I will implement this twice.
