### ISSUE TITLE
Test parity interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#234]
Due to the importance of the parity interactive, thorough testing is required. Please try using the links below and comment feedback as required. We have hosted the current version on the interactive on our department website for ease in testing. We need to test the interactive on both desktop and mobile devices.

The parity interactive runs in four different modes:
- [Parity trick mode](http://www.cosc.canterbury.ac.nz/csfieldguide/prototypes/parity/index.html) - This mode runs through the full parity trick, starts with setting parity, flipping a bit, then detecting the error.
- [Set mode](http://www.cosc.canterbury.ac.nz/csfieldguide/prototypes/parity/index.html?mode=set) - This mode allows the user to just practice setting parity.
- [Detect mode](http://www.cosc.canterbury.ac.nz/csfieldguide/prototypes/parity/index.html?mode=detect) - This mode allows the user to just practice detecting a flipped bit.
- [Sandbox mode](http://www.cosc.canterbury.ac.nz/csfieldguide/prototypes/parity/index.html?mode=sandbox) - This mode allows the user to have a sandbox environment to test different scenarios.

Thanks for your help @uccser/csfg-team.

**Comment by DrCuriosity** [comment]
I think it might be worth having tuned feedback for different error cases, e.g.:

1. At least one row and one column is incorrect
2. At least one column is incorrect
3. At least one row is incorrect
4. All rows and columns correct, except lower-right corner (i.e. parity of parity bits)

**Comment by DrCuriosity** [comment]
To make the sum cells a bit more visually distinctive from the others, it might be worth upping the CSS border size for all cells (perhaps to 2px).

**Comment by JackMorganNZ** [comment]
Thanks @DrCuriosity:
- In regards to different feedback, because of the way the parity trick works there will always be one row and one column incorrect (unless you are describing how it's set). We have discussed the use of error messages and the amount of guidance given to the user, and have left some freedom of discovery of finding errors. Thanks for bringing it up as we want to know what user's expect.
- I've had equal numbers of people say it's better at 1px or better at 2px. I'll try increasing it as we use colour to provide feedback.

Thanks for your comments.

**Comment by JackMorganNZ** [comment]
I've pushed some updates (not reflected on the prototype website) here: 2b4d5de7d7d6c9f36e407af863f642e15dd7fd38

**Comment by JackMorganNZ** [comment]
Thanks for everyone's feedback (including those through private messages). I'll close this issue as we believe the interactive is ready for use.
