### ISSUE TITLE
Exit button does not function

### ISSUE THREAD

**Issue by ner0x652** [uccser/cs-field-guide#235]
I found this bug at least in Searching Boxes part 1, version 1.9.9

How to replicate my environment:
OS: GNU/Linux Debian 8
Browser: Firefox 43.0

**Comment by saltbrain** [comment]
Came here to point to this. I'm new to this though so not sure how to go about fixing this issue.

**Comment by ner0x652** [comment]
@JackMorganNZ can you give a link to the code so we can help?

**Comment by JackMorganNZ** [comment]
I've nearly finished tidying up the code to add to the repository, I can fix this bug as I update it. Thanks for the reminder.

**Comment by JackMorganNZ** [comment]
This is fixed in 9f167d3345b1432f72d3ba3924170c7c9c9f426d, the exit button should now closes the browser tab. This is still currently on the interactive's branch, but I'll merge it into `develop` later today, to release later this week in 2.0.3.
