### ISSUE TITLE
500 – Internal Server Error when trying to download a code snippet

### ISSUE THREAD

**Issue by ner0x652** [uccser/cs-field-guide#236]
In version 1.9.9, trying to download the code from http://www.csfieldguide.org.nz/en/files/linear-binary-search-python3.py results in an Internal Server Error (500).

**Comment by JackMorganNZ** [comment]
Thanks @ner0x652, this is a known server issue. We are trying to get the server configuration sorted today.

**Comment by JackMorganNZ** [comment]
Managed to fix it within the `.htaccess` file (using [this command](https://community.webfaction.com/questions/5527/statically-serve-py-files/5600)).
