### ISSUE TITLE
Migrate from HTTP to HTTPS

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#257]
Using HTTPS gives users a secure experience, but also allows interactives to use the user's microphone and webcam.

**Comment by samjarman** [comment]
Probably can get a free SSL cert from https://letsencrypt.org/ - Would need some config on the web host.

**Comment by JackMorganNZ** [comment]
This can be easily enforced (with redirection) in the upcoming Django system.

**Comment by JackMorganNZ** [comment]
Completed in 0660b19
