### ISSUE TITLE
Add curiosity boxes explaining some of the unicode encoding schemes (at least UTF-8 and UTF-32)

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#278]
(Note that this should be done once the main text has been refactored -- I'll update this saying when that is).

This is not essential for the standard, but some students will want to know how unicode characters were assigned bit representations in encoding schemes. We should aim to at least do UTF-32, which is trivial, and UTF-8, which is more complicated, but interesting, and still accessible.

Wikipedia gives an explanation, but we'll want to explain this as clearly as possible for the students.
https://en.wikipedia.org/wiki/UTF-8#Description

Assigned this to Tim, but if you are not keen, I'm happy to do it myself :-)

**Comment by Heidirose** [comment]
Closing this as I've decided all students should understand UTF-8. Will update with a new issue later.

**Comment by JackMorganNZ** [comment]
@Heidirose Can you please link the new issue to this issue when it's created so it's easier to find.

**Comment by Heidirose** [comment]
Sure, although this issue is pretty much redundant now. If I could have hard deleted it, I would have.

**Comment by JackMorganNZ** [comment]
The goal with having our repo on GitHub is everything is stored, even if is not implemented. Because if a few years down the line someone suggests we move UTF-8 info to curiosity boxes, we can show them this issue to as proof we had discussed it at some point and decided all students should understand it.
