### ISSUE TITLE
Rename assessment guides to follow a more consistent naming convention

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#280]
Some of them are not consistent, I need to fix this.

**Comment by JackMorganNZ** [comment]
Has this been completed? We can create a `README.md` in that folder that states the correct naming convention if needed.

**Comment by Heidirose** [comment]
No, not yet. I'm the only one who works on them, so won't worry about a README.md at this stage.

It's just a 10 minute job that I'll do sometime soon :)

**Comment by Heidirose** [comment]
No longer applicable
