### ISSUE TITLE
Create numbered boxes for translation and rotation box interactives

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#281]
Need to draw three numbered boxes (1, 2, 3) in a similar style to the previous box artwork for @hayleyavw.

**Comment by hayleyavw** [comment]
ping @JackMorganNZ, nearly finished with these interactives, so the numbered boxes will be needed soon :)

**Comment by JackMorganNZ** [comment]
This has been delayed as we sort out issues with the drawing tablet drivers. May need to complete this task from my Windows machine at home.

**Comment by hayleyavw** [comment]
No problem, when you get around to it jump on to my branch and put them in the base-files/img/translation-rotation-interactives-images/ folder. Let me know when you have done so :)
