### ISSUE TITLE
Tidy up colour-matcher interactive and add binary value representation

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#285]
The following ideas could be implemented for the colour-matcher interactive:

- [x] Add binary representation of the bytes of colour data below the sliders
- [x] Add the ability to switch between binary and decimal representation on sliders
- [x] Only compare 8-bit and 24-bit values to goal colour, and not each other
- [x] Reduce the amount of vertical space used by the sliders
- [x] Separate the interactive and instructions
- [x] Make instructions able to be hidden

**Comment by JackMorganNZ** [comment]
Next steps include:

- Add optional hexidecimal display
- Improve efficiency of JS logic
- Prevent bits being clicked if help given
- Colour slider with it's computed value (only of it's colour type, so a slider 50% green will be coloured `#007700`)

**Comment by Heidirose** [comment]
I believe this issue fully covers #301 ?

**Comment by JackMorganNZ** [comment]
Yep, I'll close #301.
