### ISSUE TITLE
Provide a way of putting math in a code box

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#297]
I like to use code boxes to make things stand out/ break up the monotonous text appearence.

However, a problem I have run into is that I cannot use {math} inside code boxes.

A way to do this would be great, and would definitely improve the visual appearence of parts of the data representation chapter and others.

**Comment by JackMorganNZ** [comment]
I can create a new stylized box for content, though it will be a new type of object as code boxes have special behaviour (like syntax highlighting). I could possibly add an ignore cause if the code is plain text, but this depends on the use of the text. If MathJax text was allowed it would look odd as code blocks currently use monospace fonts.

Would you like a box for normal text (sans-serif, light text text on dark background) which allows MathJax, or were you wanting to use these boxes for code related text like pseudo code that included math?

**Comment by Heidirose** [comment]
I'd like a box for normal text, that allows MathJax to be in it. The exact same style and interface to the existing code boxes would be ideal (including the same colour scheme).

Sometimes I use boxes because I want the example to appear in fixed width (a grid of 0's and 1's is a good example of that). At this stage, I don't think there is a use case for mixing MathJax and fixed width font though. But I'd like the boxes to appear the same, regardless of which sort it is.

**Comment by JackMorganNZ** [comment]
This has been solved in #318.
