### ISSUE TITLE
Colour bit changer

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#301]
This interactive is for the representing colours subsection of the data representation chapter. The learning objective is for students to see how changing the individual bits changes the colour represented, and that the bits to the left of each colour component have a greater impact on the final result than the ones to the right.

A possible interface for 8 bit is as follows (a 24 bit one would be nice as well).
 
    RED        GREEN       BLUE
[ 0 | 1 | 1 ]   [ 1 | 0 | 0 ]    [ 0 | 1 ]
[ This here should be a box with the overall colour in it]

Students should be able to click the individual bits, and when a bit is clicked it changes it switches its value. The background of each block of bits should change as the bits change (with the amount of red, green, or blue).

Assigned to James, as he said he is keen to work on this.

**Comment by Heidirose** [comment]
@JackMorganNZ , I think this is actually redundant now? The new colour matcher interactive seems to have this functionality within it?

**Comment by JackMorganNZ** [comment]
This was completed in #285.
