### ISSUE TITLE
Write curiosity for emojis and unicode

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#308]
Additional section for the Data Rep chapter

**Comment by JackMorganNZ** [comment]
@hayleyavw Could you please be able to change text to use the `panel` syntax ([see docs here](https://github.com/uccser/cs-field-guide/blob/develop/docs/writing-text.md#panels)). Otherwise I can do it later today.

**Comment by hayleyavw** [comment]
Yeap, will do that this afternoon :)

**Comment by hayleyavw** [comment]
Done! Noticed I also used html syntax rather than markdown for the link, and didn't split the paragraph across lines. All fixed now :)
