### ISSUE TITLE
Review needed: Colour representation

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#311]
The colour representation section of the data representation chapter has had an overhaul (meaning that entire chapter has had a complete overhaul now!)

@hayleyavw or @timbellnz can you do this review?

Changes are in branch content/data-representation

**Comment by timbellnz** [comment]
I've been through and done some polishing - commit 2f797179d5041d65a5d370d39754cf222ceed594

**Comment by JackMorganNZ** [comment]
@Heidirose Can this be closed now?

**Comment by Heidirose** [comment]
I was waiting to see if @hayleyavw  also did a review before I closed it. But we could just close it now, on the basis that I'm satisfied with this review for the purposes of release 2.5 (her reading it would be a good bonus).
