### ISSUE TITLE
Write assessment guide for colour representations

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#314]

**Comment by Heidirose** [comment]
I'm going to do this for v2.6 (Shouldn't take me long), because I want to see the final state of the colour interactives first :-)

**Comment by JackMorganNZ** [comment]
@Heidirose: I believe this was completed in `v2.5.0`, can we close this?

**Comment by Heidirose** [comment]
Yes, totally forgot about this.

**Comment by JackMorganNZ** [comment]
So did I! Thanks for closing it!
