### ISSUE TITLE
Review needed: Unicode assessment guide

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#315]
The guide can be found on branch content/data-representation.

The file name is cs-field-guide/text/en/curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-text.md

**Comment by timbellnz** [comment]
Minor fixes/polishing done: commit 07ba86ad6f2e38e3844becbb2888dbf3577079cc

**Comment by Heidirose** [comment]
Thanks!

**Comment by Heidirose** [comment]
Oh by the way @hayleyavw , it's great if you can read over this too. I just closed the issue because it is no longer essential to 2.5 (but would be very helpful).
