### ISSUE TITLE
Fix formatting of sample outline in NCEA guides

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#318]
The following two guides have a suggested outline for reports near the end; currently the use a ```code``` format, but they should be formatted e.g. ***Computer Science report for 2.44*** should be a bold heading. (Alternatively, change the text in the paragraph before that refers to it as bold).

assessment-guide-level-2-excellence-data-representation-numbers.html
assessment-guide-level-2-excellence-data-representation-text.html

**Comment by Heidirose** [comment]
Main issue here is that a lot of formatting doesn't work in code boxes.

We talked about this the other day

**Comment by JackMorganNZ** [comment]
I'm working on this issue (which is also related to #297) to allow for 'text boxes'. I have also encountered  issue #324 while working on this so need to complete that issue before this can be completed.

**Comment by JackMorganNZ** [comment]
I've added the text box tags for this, here is the documentation for it:

# Text Boxes

Text boxes are used to highlight important information that don't belong in a panel, code block, or diagram. The content within the box is padded with a shaded background and bordered to draw the attention of the reader.

```
{text-box}
**Computer Science report for 2.44**

  Put your introduction to what bits are here
{text-box end}
```

**Parameters:**
- `indented` - If `True` the text box will be indented to the left to match the indentation of the first level of a list.
