### ISSUE TITLE
Correct unicode-length interactive HTML to MaterializeCSS layout

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#326]
The HTML of the unicode-length interactive needs to follow the MaterializeCSS guidelines in order to function correctly.

**Comment by JackMorganNZ** [comment]
I've made changes to the HTML in commits e870028435bb25c2bbe3f58379451ed044af5a67 and 7609426a969af8c5df2a1a4528c5ec5274cc03b1 which is available on branch `issue/326`. The JS needs to be updated as it was inserting the values into `<input>` elements which have been switched to `<div>` elements.

I cannot inspect the JS file to see if this is the case as opening the file crashes my Atom browser (probably due to the large amount of syntax highlighting, seems to be an issue occasionally when opening large files). 

@Jamesernator Could you update the JS? Probably need to use `.html()` instead of `.val()`.

**Comment by Heidirose** [comment]
It needs to be modified in the Coffee Script code, not the Java Script code.

**Comment by JackMorganNZ** [comment]
Yep, this is why I would like @Jamesernator to do it as he already has the environment set up. I don't have Coffee Script or NodeJS installed.

**Comment by Heidirose** [comment]
Ahhh, got it. Sorry, was just really confused about why you were trying to open/ look at the JS file

**Comment by JackMorganNZ** [comment]
Fixed in c41696201dc8f986bf5bc3706f68d7322a498349.
