### ISSUE TITLE
How do we pronounce "Oughter?"

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#331]
@oughter, please settle an office debate. @JackMorganNZ and I cannot decide if your username is _aww-ter_ or _otter_

:)

**Comment by oughter** [comment]
Haha :p Well I think each one of you otter decide how you want to pronounce it!
https://i.imgur.com/YaLBv6X.gifv

**Comment by hayleyavw** [comment]
This settled the dispute and provided quality lols 👍
