### ISSUE TITLE
Quicksort interactive not loading correctly

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#334]
The = quick in the URL is appearing as %3Dquick, which means that the interactive loads as the selection sort one (the default).

A student in the class I am teaching right now came across this.

This needs to be fixed asap as it is a serious bug.

**Comment by JackMorganNZ** [comment]
I'll get sorted on this ASAP, seems to be issue caused by 8632820ce19fba684dfbfcca876b81ad6762e764.
