### ISSUE TITLE
Glossary link forcing word onto seperate line

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#344]
https://github.com/uccser/cs-field-guide/blame/develop/text/en/chapters/coding-encryption.md#L583

The word "digital signature" appears on its own line.

Additionally, is this glossary link here really necessary? It seems odd to me to have it... in a box that is actually all about digital signatures. If the reader might not know what a digital signature is without clicking that link, then the contents of the curiosity box need to be made clearer.

**Comment by timbellnz** [comment]
> Additionally, is this glossary link here really necessary?

(After some discussion)... yup, it's useful as part of the whole glossary ecosystem, even if it doesn't seem that useful when the term has just been defined.
