### ISSUE TITLE
Add binary cards interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#349]
Create a binary cards interactive to emulate the CS Unplugged activity.

**Comment by JackMorganNZ** [comment]
Working prototype was created here: c26d0161f6700385afca45195ae82dffc2347d59

This prototype displays the binary cards (currently without dots) and counts the number of visible dots.

Todo:
- [ ] Draw dots on cards dynamically (while managing browser performance)
- [ ] Allow parameter to configure the numbers to display.

**Comment by timbellnz** [comment]
Thanks! How do I view it?

**Comment by JackMorganNZ** [comment]
Switch to the `interactive/binary-cards` branch, then open the folder `binary-cards` in the interactives folder and open the `index.html` file in a browser. The dots are currently missing, but it's what I'm currently working on (had to spend some time thinking about the best way for the browser to draw hundreds of dots).
