### ISSUE TITLE
Add binary-cards and base-calculator interactives into text

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#350]
## Description

The `binary-cards` and `base-calculator` interactives have been completed (#33 #34 #41 #349) and need to be linked into the text where appropriate.

**Both interactives** can be configured by the following parameters:
- `base=value` - Where `value` is the number base to use (defaults as 2).
- `digits=value` - Where `value` is the amounts of digits to display (default is 6).
- `offset=value` - Where `value` is the amount to offset the displayed digits (default is 0). Using a positive number will show the placings from the `digits` + `offset` value, for the number of given digits. For example, using a base of `10`, digits as `3`, and offset as `2` will show the 100,000, 10,000, 1,000, and 100 placings. Using a negative number for the `value` will display floating numbers.

**Also the `base-calculator` interactive**, can also use the following parameters:
- `show_power=boolean` - Shows the row showing selected value multiplied by the base to the power of the digit place. `boolean` is either `true` or `false` (defaults to `true`).
- `show_multiplication=boolean` - Shows the row showing the digit value multiplied by the selected value. `boolean` is either `true` or `false` (defaults to `true`).
- `show_value=boolean` - Shows the row showing the value of the selected value. `boolean` is either `true` or `false` (defaults to `true`).
- `show_total=boolean` - Shows the total column on the right hand side. `boolean` is either `true` or `false` (defaults to `true`).

To use any of these parameters, the interactive must be used in either `whole-page` or `iframe` mode.
### Previews
- [Binary Cards](http://htmlpreview.github.io/?https://github.com/uccser/cs-field-guide/blob/develop/interactives/binary-cards/index.html)
- [Base Calculator](http://htmlpreview.github.io/?https://github.com/uccser/cs-field-guide/blob/develop/interactives/base-calculator/index.html)

_These previews may take ~10 seconds to load as they are using a special online GitHub previewer_

**Comment by JackMorganNZ** [comment]
[The interactive can also be viewed online here](http://htmlpreview.github.io/?https://github.com/uccser/cs-field-guide/blob/develop/interactives/binary-cards/index.html) (takes a few seconds to load).

**Comment by JackMorganNZ** [comment]
Will also:

- [ ] Add button to flip all cards to black.
- [ ] Avoid uneven wrapping.

**Comment by JackMorganNZ** [comment]
I've add the features above to `binary-cards`. I will alter this issue to include adding both the `binary-cards` and `base-calculator` interactives into the CSFG.

**Comment by timbellnz** [comment]
Added supporting text with commit b93ed21f5ff60d58e9217cd647b0117ad55d7186 
Need to insert interactive at ***** marker to give 5 bits and start with them all black.

**Comment by JackMorganNZ** [comment]
Added the `start` parameter to allow specifying the starting sides of binary cards and fixed the interactive tag in `data-representation.md` to use this.

Now just need to add the `base-calculator` interactive into where it's needed.

**Comment by eAlasdair** [comment]
closed - done
