### ISSUE TITLE
5.4.4.1 How does UTF-8 Work? (example wrong)

### ISSUE THREAD

**Issue by digitalDojoNZ** [uccser/cs-field-guide#352]
## Description

Clearly and concisely describe the issue or suggestion here:

Determine that the Unicode number for 貓 is 35987.
Convert 29483 to binary -- giving 10001100 10010011.

^^  we went from 35987 to 29483

[Screenshot](https://www.dropbox.com/s/qrx07jzm1aflbcm/Screenshot%202016-06-05%2004.19.15.png?dl=0
)

### Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the issue.*

- [ ] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [ ] I have applied relevant labels

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] Which platform(s) and browser are you encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Thanks for spotting that @digitalDojoNZ, I've fixed the text in commit 650314ad2677e8b11738fab9f5b84bd90e1ace60. The correction will go live in the v2.6.0 release (should be in the next few weeks).
