### ISSUE TITLE
List sections in CSFG for NCEA Encryption RSA Cryptosystem guide

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#355]
## Description

The list for sections in the CSFG relating to this curriculum guide [is empty and has *TODO* listed](https://github.com/uccser/cs-field-guide/blame/develop/text/en/curriculum-guides/ncea/assessment-guide-level-2-encryption-rsa-cryptosystem.md#L32). The *TODO* should be removed with relevant sections added.

### Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the issue.*

- [x] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [x] I have applied relevant labels

**Comment by Heidirose** [comment]
This assessment guide is not finished, hence the reason that it has TODO(s) in it.

Consider closing this issue, as it isn't really helpful.
