### ISSUE TITLE
Fix heading spacing in curriculum guides

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#359]
The formatting and CSS for the curriculum guides needs to be improved to keep them as readable and aesthetically pleasing as possible.

- Currently, the gap between a subheading and the previous paragraph is the same size as the gap between the subheading and the following paragraph. The gap before needs to be much larger than the gap after, so that the subheadings stand out, and grouped with the correct text. This guide gives a good example of the problem, because of all the headings that are needed.
http://www.csfieldguide.org.nz/en/curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-text.html

I'll see if anybody else wants to work on this in the near future, but if not then I'm happy to take it on.

**Comment by JackMorganNZ** [comment]
While it is possible to split the CSS, I don't think it's needed here as this style should be rolled out across the whole guide. Currently the space before is only fractionally bigger than the space after, so I can make the space noticeably bigger before a heading.

**Comment by Heidirose** [comment]
That works too.

I just assumed it was wanted that way because it hadn't been done already
