### ISSUE TITLE
Add syntax for changing text colour

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#360]
Currently, the only way to do this would be to use HTML, which is against the style guidelines of the project.

For the curriculum guides in particular, text colour will be a very useful way of making the documents more reader friendly, and making certain parts stand out more than others.

I'm happy to work on this if nobody else is able to pick it up in the near future.

**Comment by samjarman** [comment]
Where's an example of this were it'd be better than italics or emphasis? :)

**Comment by Heidirose** [comment]
I should have mentioned, this will also help to make the documents more visually appealing.

Just to clarify too, I'm referring to the assessment guides (not the chapters, which are fine as they are).

**Comment by samjarman** [comment]
I think the best way forward for this would be to create a set of markdown extensions or macros that are defined in CSS and which add a class to the element by the parser.

Thoughts
 - Keep content and presentation separate
 - Designers can modify what their opinion of ‘visually appealing’ means ;) 
 - Readability for vision impaired users.

**Comment by Heidirose** [comment]
Yeah I agree, I'd also go about it like that.

**Comment by JackMorganNZ** [comment]
This can be added into the system, but before we make any major changes, @Heidirose could you please post a screenshot, say of a curriculum guide, with the text coloured to show what the end result might look like?

**Comment by Heidirose** [comment]
@timbellnz Can you please confirm that it is okay for me to spend time on this? Just might take me awhile to do as I haven't done much before in terms of modifying CSS with developer tools (which I think is the best way of doing this).

**Comment by Heidirose** [comment]
No longer relevant as we're changing the format of curriculum guides.
