### ISSUE TITLE
Slight interface bugs in delay analyser

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#362]
## Description

In delay-analyser, clicking on the green "View statistics" button when no tiles have been clicked shows the heading for the table only; it would be better to not show the heading as it would just confuse the user.

Also, when in the statistics view, pressing "Reset experiment" does indeed reset it, but the green button remains "View grid" instead of changing to "View statistics", although its behaviour changes.

Happens on Chrome on the live web version v2.6.0

### Checklist

- [x] I have linked any relevant
- [x] I have applied relevant labels

If this is a code related issue, please include the following in your description:

- [x] Steps to reproduce the behavior
- [x] Which platform(s) and browser are you encountering the issue on
- [x] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Excellent report, I can fix these bugs today.
