### ISSUE TITLE
Errors not giving line number

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#377]
## Description

When I generated the CSFG, I got an error. I had a look in the error file, and all it said was:
"29/07/2016 10:13:53 ERROR    Coding - Encryption - line Unknown: Panel type argument missing"
This isn't very helpful for finding the bug. Could we please have the line number given?

If it is difficult to give the line number, an alterative would be to put the text around the error into the error message, so that it is really easy to know where the error is (and can be found with ctrl+f).

### Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the issue.*

- [ ] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [ ] I have applied relevant labels

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] Which platform(s) and browser are you encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
All fixed in the `develop` branch. You will need to merge `develop` into any branches you are working on to see this fix take effect.
