### ISSUE TITLE
Remove JSEncrypt library

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#379]
## Description

 There are numerous bugs and problems with the RSA interactives, such as the one I mentioned in #378, and another where the message is identical regardless of whether you encrypt it with the public key or private key! (Seems to be in the no-padding one, much more difficult to test in the pure one because of the padding). Additionally:
- We can't have digital signatures with it, because looking at the repo for it, there is not proper support for encoding with private key and decoding with public key (and there has been numerous fruitless back and forth discussions on the topic, so I don't think they ever will support it).
- In general, the no-padding approach required modifying the library in ways that might have introduced other bugs (e.g. the one I mentioned above).

This library lacks features because it is designed to be used for real world cryptography applications. Releasing code that is not perfectly tested is dangerous for that use case, so the developers are being understandably cautious.

In our case however, potential weaknesses in the encryption just aren't an issue. As a learning demonstration, we need it to be a fully functioning demonstration for the students.

I am very strongly recommending that we give up on third party libraries for these interactives, and instead go back to our own one (with improvements). If we can't get to a 4KB key, then that is totally fine. The main thing we need is the general functionality, and in particular the digital signatures working. I want students to be able to do the trick where you encrypt with both your own private key AND the other person's public key, and then decrypt with the other 2 keys, and for it to work correctly.
### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the issue._
- [ ] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [ ] I have applied relevant labels

If this is a code related issue, please include the following in your description:
- [ ] Steps to reproduce the behavior
- [ ] Which platform(s) and browser are you encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by eAlasdair** [comment]
>  the message is identical regardless of whether you encrypt it with the public key or private key!

I've found that this is because digital signatures aren't supported. The private key in the format used (I assume PKCS 8) has all components of the key **including the public components** so in both cases it was being encrypted with the public key.

This will be resolved and digital signatures added in #1123
