### ISSUE TITLE
Contributors footer link broken

### ISSUE THREAD

**Issue by imnofox** [uccser/cs-field-guide#383]
## Description
The link in the footer referring to the guide's contributors is not rendered correctly.
Instead of substituting the relevant variable, the link is rendered as `{{ contributors_path }}`.
Obviously, I expected to a see a working link to the guide's contributors.

### Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the issue.*

- [x] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [ ] I have applied relevant labels

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] Which platform(s) and browser are you encountering the issue on
- [x] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Thanks for spotting this issue @imnofox! I'll be able to roll out a fix for this next week.
