### ISSUE TITLE
Fix skewed sponsor logos in PDF output

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#397]
## Description

The following image shows how the logos are skewed, these need to be restored to their original ratios.

![image](https://cloud.githubusercontent.com/assets/8001048/19585278/9740ac90-97a7-11e6-9d47-45b3d07cc7c2.png)

**Comment by pvskarthikeya** [comment]
@JackMorganNZ Hey! Can I work on this?

**Comment by JackMorganNZ** [comment]
Sure @pvskarthikeya, let me know if you need help.

**Comment by pvskarthikeya** [comment]
@JackMorganNZ  Hi! When I generate the PDF version, the images for company logos are squished to the right and cut off. I used `python generateguide.py -l en -q` for creating the pdf.
![screen shot 2016-10-27 at 7 38 05 am](https://cloud.githubusercontent.com/assets/9097958/19771886/3f9c30b0-9c19-11e6-83a1-1007599ec3b8.png)

Also attaching the generated doc for your review. [PDF generated output](https://1drv.ms/b/s!Ajxoigvdb4vigQgcUPg5N0c-Cn7K)

**Comment by JackMorganNZ** [comment]
Sorry for getting back to you @pvskarthikeya, had a family emergency all of last week. I've had this issue too when I generate the PDF on my Windows machine, but it's fine when I create it on my Linux machine. It may be a CSS issue that is being rendered differently for some reason. I'll look into it as well when I get some time (though I will be very busy the next few weeks).

**Comment by pvskarthikeya** [comment]
@JackMorganNZ  That's fine. I will try to look in to it. Dont worry about this at all. Take your time. Thanks
