### ISSUE TITLE
Move NZ specific teachers note to assessment guide

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#4]
The following sections require NZ teachers notes to be extracted and moved to assessment guides:
- [ ] Artificial Intelligence
- [ ] Computer Graphics
- [ ] Compression Coding

**Comment by JackMorganNZ** [comment]
Also the project section will need to be moved.

> Project: Investigating chatterbots and the Turing test

**Comment by hayleyavw** [comment]
A: describing the concept of encoding information using compression coding, error control coding, and encryption; and typical uses of encoded information
M: discussing how a widely used technology is enabled by one or more of compression coding, error control coding, and encryption
E: evaluating a widely used system for compression coding, error control coding, or encryption

**Comment by eAlasdair** [comment]
closed for guides out of date
