### ISSUE TITLE
Formal Languages Interactive - Washing Machine

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#411]
## Description
There are buttons to interact with the washing machine on the Formal Languages page, but they do not seem to change the state of the system.

Using Google Chrome Version 56.0.2924.87 on Windows 10

### Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the issue.*

- [x] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [ ] I have applied relevant labels

If this is a code related issue, please include the following in your description:

- [x] Steps to reproduce the behavior
- [x] Which platform(s) and browser are you encountering the issue on
- [x] The behavior you expect to see, and the actual behavior

**Comment by DrCuriosity** [comment]
Testing the [chapter](http://www.csfieldguide.org.nz/en/chapters/formal-languages.html) in both Firefox 52 and Chromium 53 on Ubuntu 14.04, the washing machine interactive is misbehaving in both browsers. Site is whitelisted in ad/script blockers.

It seems to be working as expected in standalone on both:
* http://www.csfieldguide.org.nz/en/interactives/fsa-washing-machine/

I am getting the following console errors from Chromium, though I don't know if they're directly related to the issue or not:
```
Failed to parse SourceMap: http://www.csfieldguide.org.nz/en/interactives/base-files/js/third-party/iframeResizer.contentWindow.map
Failed to parse SourceMap: http://www.csfieldguide.org.nz/en/js/third-party/iframeResizer.map
Failed to parse SourceMap: http://www.csfieldguide.org.nz/en/interactives/base-files/js/third-party/iframeResizer.contentWindow.map
```

Firefox isn't giving me any useful error messages.
