### ISSUE TITLE
Move reset button in Delay Analyser interactive away from grid

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#413]
The reset button is too close to the grid and can be accidentally clicked by users, there should be more padding between the grid and button.

**Comment by AdamB37** [comment]
I can take this on.

**Comment by JamieDawson** [comment]
I'll look into this!

**Comment by JackMorganNZ** [comment]
Hi Jamie, I saw you had commented on this issue and made a pull request (which looked perfect) and was in the process of reviewing it when it disappeared! Was this intentional?

**Comment by JackMorganNZ** [comment]
Glad to hear it got sorted out. I've actually made a support request to GitHub as a lot of our users who interact with this repository are getting flagged as bots!
