### ISSUE TITLE
Decide how to deal with licences for third-party libraries in interactives

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#450]
Typically we include this within the interactives folder, but CSU proposed storing these in a 'LICENSE-THIRD-PARTY` folder....

The decision will need to be noted in the docs.

**Comment by eAlasdair** [comment]
At some point it was decided to use the CSU method and the docs have been updated appropriately. The process of implementing it will be started by #863 

![v](https://user-images.githubusercontent.com/25916475/53533713-c33d8980-3b60-11e9-9e70-6aa12eec8b81.png)
