### ISSUE TITLE
Complete development of NCEA Guide Selector interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#477]
Currently the logic of the interactive is completed, however all NCEA guides need to be linked into it, and summary text added. It might be worth waiting until the new DT|HM curricula is confirmed before investing time into this.

**Comment by eAlasdair** [comment]
Interactive is removed in #958 

![image](https://user-images.githubusercontent.com/25916475/58139661-df4c5500-7c8f-11e9-814d-6cc4c00fed98.png)
