### ISSUE TITLE
Add keyboard manipulation of sliders for colour mixer interactives

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#496]
The slides should be able to decrease or increase the value by one using the arrow keys.

**Comment by JackMorganNZ** [comment]
@courtneycb Could we get this done soon? It's frustrating to do demonstrations requiring precise inputs currently.

**Comment by courtneycb** [comment]
> @courtneycb Could we get this done soon? It's frustrating to do demonstrations requiring precise inputs currently.

Yes sir consider it done.
