### ISSUE TITLE
Check binary search text and file

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#500]
_**The following issue is user submitted and needs to be validated:**_

On this page: http://www.csfieldguide.org.nz/en/curriculum-guides/ncea/level-1/searching-algorithms.html
The following explanation about finding the average of a binary search is wrong as this is not how you work it out, instead it is describing how to work out the worst case scenario.

> Hint for estimating binary search: Remember that with each box you look at, you are able to throw away half (give or take 1) of the boxes. Therefore, To calculate the average number of boxes that binary search would have to look at, repeatedly divide the number by 2 until it gets down to 1. However many times you divide by 2 is the average cost for binary search. Don’t worry if your answer isn’t perfect; it’s okay to be within 3 or so of the correct answer. This means that if while halving your number it never gets down to exactly 1 (e.g. it gets down to 1.43 and then 0.715), your answer will be near enough. As long as you have halved your number repeatedly until it gets down to a number that is less than 1, your answer will be accurate.

Also, the python searching code in this file needs tweaking: http://www.csfieldguide.org.nz/en/files/linear-binary-search-python3.py

In the test_linear and test_binary functions the random number to search for should be got using the following code:
item = randint(0, n - 1) not item = randint(0, n) as the searching algorithms assume zero based lists.

**Comment by JackMorganNZ** [comment]
_**Also submitted by another user:**_

Hi I was wondering if this information was correct? "Hint for estimating binary search: Remember that with each box you look at, you are able to throw away half (give or take 1) of the boxes. Therefore, To calculate the average number of boxes that binary search would have to look at, repeatedly divide the number by 2 until it gets down to 1. However many times you divide by 2 is the average cost for binary search." This is in the field guide under NCEA 91074, searching Merit/Excellence.

I was thinking this calculation works out the maximum number of possible boxes to get to the correct one. You would not always use all of the searches necessarily to find the correct box when working out averages.

**Comment by eAlasdair** [comment]
The users are correct, it is definitely the worst-case scenario and in my (not at all expert) opinion, the text should be changed.

However, it could be interpreted as: Split the number of boxes in half (even if you've found the answer), until you get to one result.
It's one fewer step in each iteration (`is it in one half` **vs** `is it the answer and if not is it in one half`) but not necessarily faster.
If it is interpreted as such then the best, worst and average cases are all identical
