### ISSUE TITLE
Add password guessing interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#606]
Text to go with interactive:

> Have a go at the following interactive. It requires you to guess the passwords of the users.
> - Alice and Bob both used passwords which are among the most commonly used 20 passwords.
> - Casey picked her password out of a dictionary. You might find hers a bit more challenging to figure out, although a computer would get it in a second. If you are keen, you might like to do a dictionary attack on it yourself.
> - Dave's password is short, but the 5 characters in it could be symbols, numbers, uppercase, or lowercase. You might find his a bit more challenging to figure out, but again it is easy for a computer and you might like to write a program to help you figure it out if you are keen.
> - Evelyn's is also a random mix of characters, but it is 16 characters long. We don't think you will ever guess her password, even if you wrote a program to help you! Do let us know if you figure it out though!
> A database is displayed, with a simple checker. For each user, you will need to copy their salt into the box, enter a possible password, and click calculate hash. The interactive will automatically notify you if the resulting hash matches one of the ones in the database above (to save you from having to carefully check the hash strings for a match)

**Comment by eAlasdair** [comment]
> Alice and Bob both used passwords which are among the most commonly used 20 passwords.

That's very ambiguous as it keeps changing: https://en.wikipedia.org/wiki/List_of_the_most_common_passwords
