### ISSUE TITLE
Create generic panel class

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#61]
Create a generic panel class for configuration of different block types (e.g. extra-for-experts, jargon-buster, hint, etc) as well as default configuration, i.e. could be used as `{panel extra-for-experts}`
or `{panel}`

**Comment by JackMorganNZ** [comment]
This should now use the following syntax:

`{panel type="extra-for-experts" summary="Information on merge sort"}`

Where the type is used for colouring the box and creating the header text, and the summary is used to describe what is within the panel. The panel's will become collapsible, hence why a summary is required. 

It needs to be discussed whether the type automatically defines the header text, for example does:

`{panel type="teacher-note" summary="Information on merge sort"}`

automatically create something like

`<div class="panel panel-teacher-note">Teacher Note: Information on merge sort</div>`

**Comment by JackMorganNZ** [comment]
Should also allow a parameter `expanded="True"` if the panel should already be opened. It defaults to False if not provided.

**Comment by JackMorganNZ** [comment]
See http://materializecss.com/collapsible.html for how panels will work in the new Material framework.
