### ISSUE TITLE
Handle translations of interactives

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#71]
Each interactive should be able to accept a translation file (possibly a .csv or .conf file) for viewing it in different languages.

**Comment by JackMorganNZ** [comment]
Thoughts for storing translations in CSV format:
- Easy to edit for users (doesn't require understanding of a more complex syntax like JSON)
- Can easily view on GitHub
- Can import into interactives using JS libraries ([PapaParse](https://github.com/mholt/PapaParse) looks great).

**Comment by JackMorganNZ** [comment]
A template file should added to the interactives `base-files` folder (#2) in order to complete this task.

**Comment by eAlasdair** [comment]
Duplicate of #2 :noot-noot:
