### ISSUE TITLE
Typo in Data Representation chapter

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#784]
Section 5.3.6.2
> Representing positive numbers with Two's Complement
Representing positive numbers is the same as the method you have already learnt. Using 8 bits, the leftmost bit is a zero and the other 7 bits are the usual binary representation of the number; for example, 1 would be 00000001, and **65 would be 00110010**.

This should either say:
> 65 would be 1000001

or 

> 50 would be 00110010

Section 5.5.3.2
In Curiosity: Hexadecimal Colour Codes
> 1001 -> **9**

Should be 5.

Section 5.5.4.2
> Have an **experiement** with the following interactive, to see what impact different numbers of bits for each colour has. Do you think 8 bit colour was right in having 2 bits for blue, or should it have been green or red that got only 2 bits?

**Comment by JackMorganNZ** [comment]
Fixed in 62ac616
