### ISSUE TITLE
Typo in Programming Languages chapter

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#787]
Section 3.2.

> It starts by adding 2 numbers (that have been put in registers $t0 and $t1) and printing out the result. It then prints “Hello World!” Don’t worry, we aren’t about to make you learn how to actually program in this language! And if you don’t really understand the program, that’s also fine because many software engineers wouldn’t either! (We are showing it to you to help you to appreciate **high level** languages!)

This should be **low level** languages.

**Comment by hayleyavw** [comment]
Not sure whether to actually consider this a typo or not, as both interpretations kind of make sense, best to check with an author to see what they were trying to say.

**Comment by JackMorganNZ** [comment]
I remember this one coming up often, could be rephrased as:

> We are showing it to you to help you to appreciate the purpose of both low and high level languages!
