### ISSUE TITLE
Local clone of CSFG repository only contains two chapters

### ISSUE THREAD

**Issue by boukeas** [uccser/cs-field-guide#797]
## Description

I cloned the repository and, following the instructions in the [installation guide](https://cs-field-guide.readthedocs.io/en/latest/getting_started/installation.html), I ran ``./csfg start``, which completed successfully. I did not keep a log of the initial run, but invoking ``./csfg start`` now outputs:

    Creating systems...
    csfieldguide_postgres_1 is up-to-date
    csfieldguide_django_1 is up-to-date
    csfieldguide_nginx_1 is up-to-date

    System is up!
    Run the command ./csfg update to load content.

The [full output](https://github.com/uccser/cs-field-guide/files/2554751/update.log) of ``./csfg update`` includes the following lines:

    Added chapter: Introduction
      Added chapter section: Beyond speed
      Added chapter section: Programming
      Added chapter section: How to use this guide
      Added chapter section: About this guide
      Added chapter section: Further reading
    Added chapter: Human Computer Interaction
      Added chapter section: Users and tasks
      Added chapter section: Interface Usability
      Added chapter section: Usability Heuristics
      Added chapter section: The whole story!
    All chapters loaded!

For some reason, **only two chapters are included**, which is also reflected in the local CSFG web-page that is loaded from ``localhost:81``

![screenshot_2018-11-06 chapters - computer science field guide](https://user-images.githubusercontent.com/11033117/48089320-e092c480-e20c-11e8-9408-348e9366b913.png)

**Comment by JackMorganNZ** [comment]
Hi @boukeas,

We are currently going through a major restructure of the system and are only partially through updating the system. We originally weren't going to switch our main GitHub branch to this until all the chapters were changed, but the restructure fixes so many issues that it was important to have developers working off it.

We have just finished the algorithms chapter and aim to have all the chapters reactivated by end of January 2019.

Was there a particular chapter you were wishing to work on?

**Comment by boukeas** [comment]
@JackMorganNZ thank you for your reply. I just wanted to make sure this wasn't a bug, or a mistake in the procedure I had followed.

> We have just finished the algorithms chapter and aim to have all the chapters reactivated by end of January 2019.
> 
> Was there a particular chapter you were wishing to work on?

I was actually interested in starting a _translation_; cloning and building the repository was a first step towards that. I would start with Data Representation but there is no schedule, so delaying until January is really no problem.

I will close this issue, but let me just point out that I could find no documentation/instructions on how to proceed with the translation (this is a parallel issue). I guess the restructure might address this as well.

**Comment by JackMorganNZ** [comment]
You are welcome your own translation, but if you are wanting to provide a translation for this website we already have systems in place for that. You can contribute translations on Crowdin here: https://crowdin.com/project/cs-field-guide

Though we haven't updated the Data Representation chapter yet to the new syntax. These changes are minimal, the core content won't be changing. We should have the syntax updated in the next week or two. I'll reply here if you want an update of when it's done.

And yes the documentation is quite out of date at the moment.

**Comment by boukeas** [comment]
I was not aware of the crowdin project. I will look into that, thank you very much.
