### ISSUE TITLE
Codehilite rendering incorrectly

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#832]
For example in the text section in the data rep chapter codehilite is rendered as:
![image](https://user-images.githubusercontent.com/16066822/50258657-8456cd80-0465-11e9-960c-8f434a8ca6d6.png)

But it should appear as:
![image](https://user-images.githubusercontent.com/16066822/50258690-a51f2300-0465-11e9-8763-9151cec64427.png)

**Comment by JackMorganNZ** [comment]
From my research this will be fixed by using Markdown 3.0+ which needs to be updated through Verto. However this is not a simple upgrade so do not know when we expect to complete this.
