### ISSUE TITLE
Improve database query performance on interactive list page

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#846]
Currently this page is performing a large number of queries that is taking a long time to load.

**Comment by courtneycb** [comment]
Have done some investigation but didn't manage to solve this.

Things that may be helpful if someone picks this up in the future:
- The troublesome queries seem to be coming from interactive-link.html 
- In interactive-link.html the DB gets hit for 'interactive.translation_available' and 'interactive.name'
- The interactive-link template gets called from templates/interactives/index.html
