### ISSUE TITLE
Interactive thumbnails not deployed

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#858]
Currently all interactive thumbnails are not showing: https://cs-field-guide-dev.appspot.com/en/interactives/

**Comment by eAlasdair** [comment]
On further inspection it was found that an error is raised when building the thumbnails for the dev site

**Comment by eAlasdair** [comment]
New problem: The path the thumbnails are retrieved from `static/img/interactives/thumbnails` does not exist on the server
