### ISSUE TITLE
Docker Volumes are never removed

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#906]
Every time the command `./csfg start` is run, Docker creates two new Volumes - one for Django, and one for Nginx. These should probably be removed by `./csfg end`, but are not, nor are they removed by `./csfg clean`.

We should implement functionality that removes unused Volumes

In the interim, if the multitudes of Volumes are affecting available storage space, this command will remove **ALL** Docker volumes (*including those unrelated to the Field Guide*):

`docker volume rm $(docker volume ls -q)`

And this will remove as much of everything (else) as possible:
`docker system prune -a`

**Comment by courtneycb** [comment]
We should follow what CSU does and add the following to `cmd_end` in `csfg`:

```
echo "Deleting system volumes..."
volumes=($(docker volume ls -qf dangling=true ))
for volume in "${volumes[@]}"; do
    docker volume rm "${volume}"
done
```
