### ISSUE TITLE
Box Manipulation interactives don't load properly

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#913]
The interactives use a library -`three`- for graphics rendering.
`three` functions attempt to load images from the server, but are denied - see below.

I cannot work on this as I don't have any access to the server

Resources that could help:
https://stackoverflow.com/questions/40099566/three-textureloader-load-image-fail-no-access-control-allow-origin-header-is
https://discourse.threejs.org/t/textureloader-with-external-image-link-cors/2343

![image](https://user-images.githubusercontent.com/25916475/56166212-1a23f300-6029-11e9-988f-b7d162dcf1c6.png)

**Comment by courtneycb** [comment]
I have resolved this issue by configuring the CORS configuration on the cs-field-guide-dev bucket. The origins we now allow are:

`https://cs-field-guide-dev.appspot.com` and `http://csfieldguide.org.nz/`
