### ISSUE TITLE
Issue with RE Filter interactive on dev site

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#927]
With the same CORS header problem as #913, The Regular Expression Filter interactive fails to load the text file it uses and the error below is shown

![image](https://user-images.githubusercontent.com/25916475/57051646-90d21900-6cd6-11e9-828e-dd935a73ab4d.png)

**Comment by courtneycb** [comment]
Have done some investigating. The server doesn't have an `Access-Control-Allow-Origin` response header which causes the CORS request to fail (as it is required).

Here are some useful links:
https://www.html5rocks.com/en/tutorials/cors/
https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work
https://cloud.google.com/storage/docs/configuring-cors

The last link tells us how to configure CORS on a bucket. We need to add an `Access-Control-Allow-Origin` header indicating which origin sites are allowed.

**Comment by courtneycb** [comment]
I have resolved this issue by configuring the CORS configuration on the cs-field-guide-dev bucket. The origins we now allow are:

`https://cs-field-guide-dev.appspot.com` and `http://csfieldguide.org.nz/`
