### ISSUE TITLE
Issue with RE Search interactive on dev site

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#928]
This is what it should look like:

![image](https://user-images.githubusercontent.com/25916475/57051841-a98efe80-6cd7-11e9-8e30-df88dadb831a.png)

This is what it does look like:

![image](https://user-images.githubusercontent.com/25916475/57051859-be6b9200-6cd7-11e9-8eb6-96ad20c8d9cc.png)

**Comment by courtneycb** [comment]
`codemirror.css` can't be found on the dev site
