### ISSUE TITLE
Travis issue

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#931]
Since late last week (early May) Travis has been regularly encountering this issue when testing branches on Github. It is always django-haystack and it happens on ~2/5 of all test runs. As we have multiple test runs per Travis build, the builds fail almost every time they are run.

This is the link in the screenshot:
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

![image](https://user-images.githubusercontent.com/25916475/57258585-f6e0e680-70b0-11e9-9fab-c6a207f26dff.png)

- This is the latest version of django-haystack, from March 2018

**Comment by eAlasdair** [comment]
This issue is separate from read timeout errors, which seem to be dealt with appropriately

![image](https://user-images.githubusercontent.com/25916475/57259633-51c80d00-70b4-11e9-9d2c-8e8e935e25e5.png)

**Comment by eAlasdair** [comment]
The issue has been narrowed down to a set of instructions that aren't normally run while we develop, specifically line 18 (i.e. Step 7/10) in `Dockerfile-local`:
`RUN /docker_venv/bin/pip3 install -r /requirements/local.txt`

This is during the `Building django` stage of `./csfg build`.
![image](https://user-images.githubusercontent.com/25916475/57262204-3f070580-70bf-11e9-8f12-6ef06f16a14a.png)
Normally `./csfg build` skips this, as its already been done.
![image](https://user-images.githubusercontent.com/25916475/57262289-a6bd5080-70bf-11e9-8ece-586cb61eab17.png)
But if I wipe **everything** (or at least as much as possible) to do with Docker with the following command, `build` is forced to run it:
`docker system prune -a`

Since `build` now has to redownload everything this takes a while, so I'm doing 5 tests to see if any fail in the same place as Travis

**Comment by eAlasdair** [comment]
All 5 completed the 10 steps without issue, so nothing can be concluded

**Comment by eAlasdair** [comment]
All 5 runs again completed the 10 steps without issue, so nothing can be concluded. django-haystack takes longer than the others to be retrieved, but still just a second or two - nothing near the 10 minutes required for Travis to time out

**Comment by eAlasdair** [comment]
From my research so far:
- It is **unlikely:**
  - A problem with the build, as it is unchanged and has worked locally in all tests
  - A problem with django-haystack, as it is unchanged, has worked locally on all tests, and on Travis the download does work ~3/5 of the time
  - A problem with the download taking too long, as it takes just a second or two on every successful test
  - A read timeout error, as there is evidence that these are handled appropriately

- It **could** be:
  - Related to a change elsewhere in the field guide between October 10 2018 and April 23 2019; I reran Travis on #721 (a very old branch) twice and it completed the 10 steps successfully in all 20 runs, but I reran Travis on #890 (a more recently updated branch) and it failed once.
  - Related to how the project is slowly increasing is size; it succeeded in all 20 runs as of #721, failed once as of #890, and is now regularly failing
  - A problem with Travis itself, as it has worked locally on all tests

**Comment by JackMorganNZ** [comment]
It would be worth logging a support ticket with Travis as they could look at network traffic for the jobs to check if it's something behind the scenes.

Also we could load that requirement from a different source as a work around until the problem is found.

**Comment by eAlasdair** [comment]
Today everything seems to be working again, Travis has so far run the 10 steps without issue every time its run, with only one issue elsewhere

![image](https://user-images.githubusercontent.com/25916475/57337351-20674400-717d-11e9-8eca-af6a9202b573.png)

**Comment by eAlasdair** [comment]
It happens a lot less often since it's needed on just the one run, but the above timeout during the `Build Documentation` test is not a once-off

**Comment by eAlasdair** [comment]
No further issues after a week, so I believe nothing needs to be done on our part
