### ISSUE TITLE
Search button is the wrong colour

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#934]
The search button appears grey on the dev site currently.

![image](https://user-images.githubusercontent.com/16066822/57341048-d5edc380-718c-11e9-8ecc-e7ef14b5115c.png)

**Comment by eAlasdair** [comment]
Notably the only difference in the css is that it lacks .btn-outline-light but that just adds the white outline, not the colour
![image](https://user-images.githubusercontent.com/25916475/57346016-1a835a00-71a1-11e9-86a5-10c70bd267d5.png)

**Comment by eAlasdair** [comment]
Actually the other difference is that its getting all of its css rules from website.css, whereas on my older branch it gets the rules from `_navbar`, `_buttons`, `_print` and so forth

**Comment by courtneycb** [comment]
Appears to be happening to other buttons across the site. This button should be green as it has the `btn-success` applied to it.

![image](https://user-images.githubusercontent.com/16066822/57413117-245f9880-7247-11e9-89cc-392a5d3d7386.png)

**Comment by courtneycb** [comment]
Maybe even _all_ buttons except ones with the `btn-primary` class...

**Comment by courtneycb** [comment]
In #932 we overid `$theme-colours` which stores the colours for all of bootstraps themes. Since we updated this to:

```
$theme-colors: (
    "primary": $csfg-light
);
```

It means all themes other than primary are not defined. We need to update just the primary theme instead of all theme colours. Great user testing by me.....

**Comment by eAlasdair** [comment]
I also should have caught that, I thought the buttons I saw were meant to be grey :/
