### ISSUE TITLE
Issue with Packet Attack Interactive on dev site

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#945]
Packet Attack is failing to load with the same CORS header issue as in #927 and #913

![image](https://user-images.githubusercontent.com/25916475/57588606-c1357500-756a-11e9-940a-c680fa0425f4.png)
 
Secondly, the custom font used `Open Sans` is blocked because it is an `HTTP` request within an `HTTPS` page (more info [here](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_active_content))
The simplest fix would just be to change the font

**Comment by courtneycb** [comment]
I have resolved the CORS header issue
