### ISSUE TITLE
Chapter section buttons don't align nicely when the title is long.

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#949]
Need suggestions on what we should do here.

![image](https://user-images.githubusercontent.com/16066822/57658623-b7c40f80-7633-11e9-9d06-241948202195.png)

![image](https://user-images.githubusercontent.com/16066822/57658626-bbf02d00-7633-11e9-87a5-1b07c26b855c.png)

**Comment by eAlasdair** [comment]
Will see if I can align them left if they don't fit
