### ISSUE TITLE
Curriculum Guides missing

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#967]
![image](https://user-images.githubusercontent.com/25916475/58389256-f2d73180-807c-11e9-8d87-d19e58771b78.png)

Although it exists in the repo (though out of date?), none of the information from the Curriculum Guides sections ([NCEA](http://csfieldguide.org.nz/en/curriculum-guides/ncea/index.html) & [AP-CSP](http://csfieldguide.org.nz/en/curriculum-guides/apcsp/index.html)) have been refactored for the new system

**Comment by Heidirose** [comment]
I can't speak for the AP-CSP guides, but I do know that the NCEA guides are now out-of-date, as the achievement standards, they were written for changed substantially.

**Comment by courtneycb** [comment]
I have been told that the AP-CSP guides are current, so we should pull them across.
