### ISSUE TITLE
Suggestions for sorting boxes interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#972]
_**This issue is user submitted and needs to be validated:**_

I'm loving the new sorting widget in the 'sneak peak' version of the guide.  I'm wondering if it would be possible to make it a lot more obvious when the boxs are / are not in order.  It is super easy to misread the statement at the bottom.  If the boxes are in order, would it be possible to have the text in blue / green with a smiley face?  Having the phrase 'Congratulations these are in order' as a success message would make things very easy.  Are fireworks / some other type of animated celebration at this point out of the question?

Likewise if the order is not correct, having a message saying 'Sorry, the boxes are not yet in order' <in red> would help make things really clear.

Also, I've noticed that the initial order of the boxes doesn't seem to be random.  When I do an insert sort going from heavy to light, the number of comparisons is generally quite low (between 13 and 20).  If I use the same method but go from light to heavy, I end up needing 24 - 27 comparisons which is verging on the worst case.  Whilst the boxes are not quite reversed, it seems like much of the time they are *almost* reversed.

**Another piece of feedback:**

I really like the sorting widget in the 'sneak peak' of the guide.  Combining both interactive (and simplifying) the scale is working well.

Can you please consider putting in a 'reset' button so that if the boxes are not in order, it is easy to reset the page and try again.

Also, I would love to be able to choose the type of data (random, nearly sorted, few unique and reverse).  Being able to get students to sort with different data types, using different algorithms be massively helpful in teaching the 'search / sort' topic at level 1.  

Ultimately it would be great to have a button that students could push that says 'show sort' for a given algorithm and data-type.  For this option making the box transparent and showing the value inside would potentially help students to see exactly how the algorithm should be implemented.

:)

**Comment by eAlasdair** [comment]
To summarise:

### Fairly simple fixes
- [ ] Make it more obvious when the boxes are/are not in order
- [ ] Improve randomisation of boxes
- [ ] Add reset button (ideally back to the original unsorted order with the same numbers)

### More long term suggestions
- [ ] Add choices for types of data to sort (random, nearly sorted, reverse, etc)
- [ ] Add further features for teaching students how to do the sorting

**Comment by eAlasdair** [comment]
I did some tests to check the randomisation of boxes. The code is an adapted form of [this algorithm](https://bost.ocks.org/mike/shuffle/) (the [Durstenfeld variation of the Fisher-Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm)) which is itself a good method of randomisation.

To check the 'randomness' of the boxes I summed the displacement of each box in each test, so for example, for the boxes:
0|1|2|3|4|5|6|7
And the shuffled form:
2|6|5|7|1|0|4|3
The differences are:
2|5|3|4|3|5|4|4
Which is a sum of 28.

The maximum value 32 can be obtained when the order is reversed:
7|6|5|4|3|2|1|0
or when the boxes are in the correct order but displaced by 4:
4|5|6|7|0|1|2|3
The minimum number is 0 where the boxes are sorted.

- In 8 tests the average displacement sum was 21.5, or an average of 2.69 per box.
- A displacement of 4 (where the box is where it would be if the boxes were in reverse order) occurred 11 times over 5 tests (in the other 3 it didn't occur), an average of 1.4 times per test.
- I didn't see anything that looked like the boxes were not sorted randomly, certainly not in reverse order.

So I can't conclude that the randomisation algorithm is *not* working as intended. But with so few tests and a method of testing I came up with on the spot I also can't say it *is* working as intended.
I can conclude:
- It was not implemented as [Sattolo's Algorithm](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Sattolo's_algorithm) (a minor implementation error) as in my tests boxes were occasionally placed in their original locations.
