### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#980]
- [x] Update 'homepage'

**Getting started**
- [x] Add VSC to IDE's we love :stuck_out_tongue: 
- [x] Update tree diagram of project structure
- [x] Investigate if `./csfg clean` actually works and if not add something about pruning docker images and containers
- [x] Are we going to reference `./csfg` or `./dev` throughout these docs?
- [x] Maybe update the dev command section since `dev` is redundant now
- [x] "(we will cover this command in more detail on the next page)" - in regards to ./csfg start but it is never explained on the next page, which is project structure. We should mention the helper commands page instead.

**Author documentation**
- [x] Update writing philosophy section - **deleted and added points under writing guide**
- [x] Update understanding config files section
- [x] Fix tree formatting in Chapter content > config files section
- [x] Update chapter content section
- [x] Update content style guide section
- [x] Update translations section
- [x] remove scratch example for verto from writing guide and use panel example

**Developer documentation**
- [x] Add interactives to django application list - should we add search..?
- [x] Add database structure diagram for models
- [x] Update web design page
- [x] Add appendices app page
- [x] Update general application page 
- [x] Update interactives page (directory structure, thumbnails etc)
- [x] Add page about search feature
- [x] Update deployment page
- [x] Update test suite page
- [x] Add translation section
- [x] Add translation infrastructure section
- [x] Add documentation about generated thumbnails under static files section
- [x] Add documentation about uninteractives under interactives section - **wording needs to be checked**

**Other**
- [x] Check VM steps still correct - **What do we do about recommended memory allocation? 20GB got eaten up fast on my machine...**
- [x] Add a troubleshooting section
- [x] Check recommendation of 4 space indents for sub-lists (rather than 2)

**Comment by eAlasdair** [comment]
- [ ] Check installation instructions, particularly steps 8 & 9

**Comment by eAlasdair** [comment]
Some more suggestions:

- [ ] Explain how to *uninstall* the field guide (end, wipe, etc), community devs won't want all their harddrive space clogged up. And perhaps mention #906 
- [ ] Expand Docker installation instructions - even I've still never done this properly

**Comment by courtneycb** [comment]
Hey @eAlasdair :)

> Expand Docker installation instructions - even I've still never done this properly

What part did you have trouble with?

**Comment by eAlasdair** [comment]
> > Expand Docker installation instructions - even I've still never done this properly
> 
> What part did you have trouble with?

I think I just ended up just following the terminal prompts and running `sudo [something] install docker` until it installed the version I wanted. Anything better than that is a good start, especially mentioning that you're meant to have an account or something(?)

**Comment by courtneycb** [comment]
Do you remember following the command on this page? https://docs.docker.com/install/linux/docker-ce/ubuntu/

Will mention the account thing

**Comment by eAlasdair** [comment]
> Do you remember following the commands on this page? https://docs.docker.com/install/linux/docker-ce/ubuntu/

Oh yeah, tried and failed that twice on two different machines (can't remember the error), didn't bother the next times

**Comment by eAlasdair** [comment]
Suggestions to add to content style guide, mostly inspired by the conversation between Jack and Hayley in #570:

## Capitalisation

- [ ] Capitalise the first word of every title/heading/sentence/this is obvious so we may not need to say it
- [ ] Capitalise every word in a major title, i.e. `Human Computer Interaction` the chapter
- [ ] Capitalise only the first word per sentence in a lesser title or heading, i.e. the `The whole story!` chapter section
  - [ ] For this purpose, a colon does count as the end of a sentence, i.e. `Analysis: What do we build?`
- [ ] Capitalise acronyms/abbreviations, i.e. `Transport layer protocols - TCP, UDP `
- [ ] If a heading includes a proper noun, capitalise it appropriately. Couldn't find a good example, something like a chapter section: `Who was Ada Lovelace?`

## Separators

- [ ] Use a hyphen to hyphenate words, i.e. `Double-barrelled` words
- [ ] Use `&ndash;` to add supplemental information, i.e. `Do this &ndash; it does something!`

## Spelling

- [ ] Use New Zealand English, which for the most part is British English
- [ ] Consider linking to [that spelling guide I made ](https://github.com/uccser/uccser-extras/blob/master/english-spelling-guide.md) for specific examples for spelling

## Other

- [ ] If you are unsure, **be consistent**. Look for examples of how its used elsewhere and let us know if it's inconsistent or doesn't make sense
