### ISSUE TITLE
Add inclusive examples to new UX content

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#992]
Extra personas should be made with an interactive that lets users swipe between them to be more inclusive

**The examples for target users would need to be different - as the content is about Uni/HS students**

This conversation is here: https://github.com/uccser/cs-field-guide/pull/990#discussion_r290067404

**Comment by JackMorganNZ** [comment]
Thanks @eAlasdair. You can also link to a comment by clicking the timestamp to get a permalink (same as Twitter, Facebook, etc).

https://github.com/uccser/cs-field-guide/pull/990#discussion_r290067404

**Comment by courtneycb** [comment]
> The examples for target users would need to be different - as the content is about Uni/HS students

Can you please elaborate on this?

**Comment by eAlasdair** [comment]
> Can you please elaborate on this?

![image](https://user-images.githubusercontent.com/25916475/58847435-1894b400-86d7-11e9-9410-a0e37d2420bc.png)

So we can't use the examples of a wheelchair-bound author and nurse etc, we need to use students

**Comment by JackMorganNZ** [comment]
Will if the text says so, then we should definitely do it! Might be good to add more references to the text that this app is for students because I either missed it or forgot, thought it was for any sleepy people. Could go either way I guess.

**Comment by eAlasdair** [comment]
Resolved in #995/#990
